In [74]:
import pandas as pd
import warnings
warnings.simplefilter(action='ignore', category=pd.errors.PerformanceWarning)
# df = pd.read_excel("C:\\Users\\user\\Desktop\\logic\\example.xlsx")
# df

In [75]:
import random
regions = ['한국']
schools = ['행과고']
grades = [1, 2, 3]
classes = list(range(1, 6))
numbers = list(range(1, 31))
genders = [1, 2]  # Assuming 1 = Male, 2 = Female
names = ['홍길동']
A_columns = [f'A{i}' for i in range(1, 25)]
B_columns = [f'B{i}' for i in range(1, 31)]
C_columns = [f'C{i}' for i in range(1, 61)]
D_columns = [f'D{i}' for i in range(1, 31)]
E_columns = [f'E{i}' for i in range(1, 61)]
test_date = ['2024-11-29']

# Generate 100 random entries
random_data = []
for _ in range(10000):
    entry = {
        '지역': regions,
        '학교명': schools,
        '학년': random.choice(grades),
        '반': random.choice(classes),
        '번호': random.choice(numbers),
        '성별': random.choice(genders),
        '성명': names,
        '검사일': test_date,
    }
    # Random scores for A, B, C, D, E columns
    entry.update({col: random.randint(1, 4) for col in A_columns})
    entry.update({col: random.randint(0, 2) for col in B_columns})
    entry.update({col: random.randint(0, 2) for col in C_columns})
    entry.update({col: random.randint(0, 2) for col in D_columns})
    entry.update({col: random.randint(0, 2) for col in E_columns})
    random_data.append(entry)

# Create DataFrame
df = pd.DataFrame(random_data)
df

,지역,학교명,학년,반,번호,성별,성명,검사일,A1,A2,A3,A4,A5,A6,A7,A8,A9,A10,A11,A12,A13,A14,A15,A16,A17,A18,A19,A20,A21,A22,A23,A24,B1,B2,B3,B4,B5,B6,B7,B8,B9,B10,B11,B12,B13,B14,B15,B16,B17,B18,B19,B20,B21,B22,B23,B24,B25,B26,B27,B28,B29,B30,C1,C2,C3,C4,C5,C6,C7,C8,C9,C10,C11,C12,C13,C14,C15,C16,C17,C18,C19,C20,C21,C22,C23,C24,C25,C26,C27,C28,C29,C30,C31,C32,C33,C34,C35,C36,C37,C38,C39,C40,C41,C42,C43,C44,C45,C46,C47,C48,C49,C50,C51,C52,C53,C54,C55,C56,C57,C58,C59,C60,D1,D2,D3,D4,D5,D6,D7,D8,D9,D10,D11,D12,D13,D14,D15,D16,D17,D18,D19,D20,D21,D22,D23,D24,D25,D26,D27,D28,D29,D30,E1,E2,E3,E4,E5,E6,E7,E8,E9,E10,E11,E12,E13,E14,E15,E16,E17,E18,E19,E20,E21,E22,E23,E24,E25,E26,E27,E28,E29,E30,E31,E32,E33,E34,E35,E36,E37,E38,E39,E40,E41,E42,E43,E44,E45,E46,E47,E48,E49,E50,E51,E52,E53,E54,E55,E56,E57,E58,E59,E60
0,[한국],[행과고],2,2,27,1,[홍길동],[2024-11-29],1,4,4,2,2,3,1,2,4,3,2,4,4,4,2,3,2,3,4,3,1,1,1,2,0,1,0,1,2,2,2,2,1,2,2,0,1,1,2,2,0,1,2,2,2,0,0,2,0,2,0,0,0,2,1,2,1,1,0,1,1,1,1,1,0,2,1,2,1,1,1,1,1,0,0,2,0,1,2,2,2,0,1,1,0,0,1,0,1,0,2,1,2,1,1,1,2,0,2,0,0,2,0,0,1,0,2,2,1,2,0,1,2,1,2,1,1,1,1,1,0,2,2,1,1,2,0,2,2,0,0,0,1,0,0,0,2,0,1,2,1,1,2,2,2,1,1,1,2,2,2,2,1,1,1,1,0,2,0,1,1,0,1,2,2,1,0,2,0,2,1,1,0,1,0,0,2,2,0,2,0,0,1,1,0,2,2,1,0,1,1,0,1,0,2,0,1,0,1,1,2,1,0,0
1,[한국],[행과고],3,5,17,2,[홍길동],[2024-11-29],1,2,2,1,4,3,3,2,3,1,4,1,1,4,2,4,4,3,2,2,4,3,4,3,0,0,1,1,1,1,1,0,0,2,2,1,2,1,2,2,0,1,0,1,1,0,1,0,1,1,1,0,2,2,2,0,1,2,1,2,2,0,1,2,0,2,0,2,2,2,2,2,0,2,0,2,0,2,2,2,0,2,2,0,1,0,0,0,0,0,2,2,2,0,1,0,2,1,2,0,0,1,2,1,2,0,1,1,0,0,2,1,0,1,2,1,0,2,1,1,0,2,2,2,1,1,2,2,2,2,0,2,2,2,0,2,2,0,2,0,0,2,2,0,0,0,1,0,0,2,1,0,0,0,1,1,2,1,2,2,2,1,2,2,2,2,1,2,0,2,2,2,0,2,0,1,1,2,2,0,0,0,0,1,1,2,0,0,2,1,1,0,2,0,1,1,1,2,2,2,2,1,1,2
2,[한국],[행과고],3,3,20,1,[홍길동],[2024-11-29],3,1,1,2,3,1,1,4,1,4,3,4,2,3,3,2,1,4,2,1,4,3,4,4,2,1,2,2,0,0,1,0,2,1,2,1,2,0,0,2,2,2,2,2,1,1,0,1,1,1,2,1,1,2,2,2,0,1,0,2,1,1,2,2,1,2,2,1,2,2,1,1,2,0,1,2,2,2,1,2,0,1,1,0,1,2,0,2,2,2,2,1,0,1,1,0,1,0,1,0,0,1,0,2,0,0,1,0,0,2,1,2,1,0,1,2,1,1,0,2,0,2,2,0,2,1,1,0,2,2,0,0,0,0,0,0,1,1,2,0,2,0,2,1,1,2,2,0,0,0,0,1,2,1,1,0,0,2,2,0,1,1,1,0,0,2,2,0,2,1,0,2,2,2,1,1,0,0,2,1,1,2,1,1,1,2,2,1,0,0,2,0,1,0,0,2,0,1,0,2,2,2,2,2
3,[한국],[행과고],2,3,9,2,[홍길동],[2024-11-29],3,3,1,1,3,3,3,4,4,2,3,3,2,2,4,2,4,4,2,2,2,2,1,3,2,1,2,0,1,0,0,1,0,1,1,2,1,1,0,0,1,2,0,2,2,2,0,1,2,1,1,2,0,0,0,0,2,0,0,0,0,1,2,0,1,2,2,0,1,1,0,1,0,2,2,2,1,2,0,2,2,1,0,1,1,0,1,1,0,1,2,1,0,0,0,2,1,0,2,2,1,1,0,0,1,2,2,0,0,2,2,2,1,0,0,1,0,1,0,1,1,2,0,2,1,2,0,0,1,2,1,1,1,2,0,0,2,0,2,1,2,2,0,2,0,0,1,0,0,1,2,1,0,2,2,2,2,1,1,1,1,1,0,1,0,0,2,0,1,1,2,2,1,0,1,0,0,0,2,0,2,2,2,2,2,2,0,0,1,2,2,2,0,1,1,2,2,1,2,2,2,0,2,2
4,[한국],[행과고],1,1,7,1,[홍길동],[2024-11-29],3,3,4,3,3,3,3,3,3,1,3,3,2,2,1,4,1,2,1,2,1,2,3,4,0,0,2,1,2,1,1,0,2,2,2,0,2,1,0,2,1,2,0,1,0,1,2,2,0,0,0,2,1,2,1,2,0,2,1,1,1,2,0,1,1,1,0,0,2,1,2,0,2,1,1,0,2,1,1,1,0,1,1,1,1,1,2,2,2,2,1,0,0,2,2,1,2,2,1,2,1,1,2,2,1,1,2,2,1,1,0,2,2,1,0,0,1,1,1,2,2,1,2,2,0,1,0,2,1,2,1,0,1,2,0,1,2,0,1,1,0,1,2,1,2,1,2,1,2,2,2,2,1,1,1,0,1,1,1,2,2,1,1,0,0,0,1,2,2,1,0,0,2,1,2,0,1,1,1,0,2,1,0,0,2,2,2,0,2,1,2,0,2,1,1,0,1,0,2,2,1,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,[한국],[행과고],1,1,29,1,[홍길동],[2024-11-29],2,2,2,1,2,1,1,1,1,1,2,2,1,4,3,1,4,2,1,3,1,2,2,1,0,0,2,2,1,2,1,1,2,2,2,1,2,0,0,2,1,1,0,1,1,0,2,1,1,2,1,0,0,1,1,1,2,0,2,0,1,2,1,2,1,1,2,2,2,2,2,2,0,2,1,1,0,2,0,2,2,1,1,0,2,0,1,1,1,1,1,0,1,2,1,1,0,1,2,2,2,0,2,1,1,2,2,0,0,1,2,0,2,1,2,0,2,1,1,2,1,2,2,2,0,2,0,1,1,2,2,0,0,0,0,2,0,0,1,2,2,2,2,2,1,2,1,2,0,2,1,0,1,0,0,1,0,0,2,1,0,0,0,2,1,1,2,2,1,1,1,0,2,0,0,2,0,0,2,1,0,2,1,1,0,1,0,1,2,1,1,2,1,1,2,2,2,0,0,2,1,1,2,2
9996,[한국],[행과고],2,4,8,1,[홍길동],[2024-11-29],3,1,3,3,3,3,4,3,3,4,1,2,1,1,1,1,1,4,3,1,3,3,3,1,2,2,0,0,0,1,2,1,0,2,1,1,1,0,2,1,1,1,0,2,1,0,1,0,1,1,1,2,1,2,1,2,0,0,2,1,0,2,1,2,2,2,1,1,2,2,1,0,1,2,0,2,0,2,1,0,1,1,0,1,0,1,1,0,2,1,0,2,2,1,0,0,2,1,2,0,0,2,0,1,2,0,2,0,1,0,2,2,2,2,2,0,1,0,0,0,2,1,1,0,0,2,1,2,0,1,1,1,2,2,2,2,1,1,1,1,0,2,1,2,2,0,2,1,1,1,1,0,2,0,0,1,2,0,1,0,2,0,2,1,2,2,2,1,1,1,2,2,2,2,0,0,0,2,0,0,0,0,1,2,1,0,1,0,1,1,0,1,1,0,1,1,0,1,2,0,0,1,0,1
9997,[한국],[행과고],1,4,17,2,[홍길동],[2024-11-29],1,4,3,3,4,1,3,1,3,1,2,4,3,1,2,4,3,2,1,4,3,4,2,3,0,2,1,1,1,1,1,0,0,0,0,1,1,2,0,1,2,0,2,2,2,0,2,1,1,2,1,0,0,0,2,0,2,0,0,1,1,1,0,2,2,2,1,0,0,1,1,0,1,1,2,1,0,0,2,1,0,1,2,2,0,1,2,0,1,2,0,1,0,2,1,2,1,0,1,1,0,2,0,1,2,2,0,1,1,2,0,2,1,0,2,1,2,1,2,0,0,2,1,0,1,0,0,0,2,1,1,0,0,0,1,0,1,2,1,0,1,0,0,1,2,2,1,2,0,1,1,0,0,0,0,2,1,1,0,1,0,0,2,1,2,0,2,1,1,2,0,1,0,1,0,0,2,2,0,0,1,0,0,0,1,2,2,1,2,1,2,2,2,1,0,0,0,1,1,0,2,0,0,0
9998,[한국],[행과고],3,3,13,2,[홍길동],[2024-11-29],1,1,2,2,4,3,2,4,3,1,2,1,3,2,4,1,3,1,4,3,3,2,4,3,0,1,0,1,2,2,2,2,2,0,1,0,1,2,1,0,1,1,1,1,0,2,0,2,2,0,1,2,0,1,1,0,0,2,1,0,1,0,2,1,0,2,0,1,0,1,1,2,0,1,2,1,0,2,0,2,0,2,0,1,0,0,2,2,2,1,0,1,1,1,0,1,0,0,0,0,0,2,1,0,1,2,2,1,2,1,0,1,2,1,2,0,0,2,2,1,0,2,1,0,1,1,1,2,0,1,1,1,2,1,2,0,2,1,1,0,2,0,0,2,2,0,0,1,0,0,0,0,0,0,0,2,1,2,0,1,2,0,2,0,1,0,0,1,2,0,1,2,0,0,2,2,1,1,0,0,1,1,1,0,0,2,1,0,2,0,0,0,0,1,0,0,1,1,1,1,1,0,2,1
9999,[한국],[행과고],1,3,15,1,[홍길동],[2024-11-29],2,4,2,3,1,4,1,2,2,1,2,1,1,2,2,3,4,1,3,1,4,1,2,1,0,0,0,1,2,2,1,2,1,1,1,1,0,1,2,1,2,1,0,2,2,2,2,2,1,2,1,2,2,0,1,2,2,2,0,1,1,0,2,1,2,0,1,0,1,1,1,0,1,0,1,1,0,0,0,1,1,1,2,2,0,0,0,0,2,2,2,2,0,0,1,2,1,0,1,0,0,2,1,0,0,2,2,1,1,1,0,1,1,0,0,2,1,2,0,2,0,0,2,2,0,0,0,2,1,0,2,0,1,0,1,2,0,0,0,2,2,1,2,2,0,2,0,0,2,0,1,1,0,2,0,1,1,0,2,2,1,0,2,1,0,2,2,2,2,0,1,1,2,1,1,2,2,0,1,0,2,0,2,0,2,2,1,1,2,0,0,2,2,2,0,0,0,1,2,1,1,0,1,2

In [76]:
##전처리 하기위해 새로운 데이터 프레임 생성
df_prepro = df.iloc[:,0:7]
df_prepro

        지역    학교명  학년  반  번호  성별     성명
0     [한국]  [행과고]   2  2  27   1  [홍길동]
1     [한국]  [행과고]   3  5  17   2  [홍길동]
2     [한국]  [행과고]   3  3  20   1  [홍길동]
3     [한국]  [행과고]   2  3   9   2  [홍길동]
4     [한국]  [행과고]   1  1   7   1  [홍길동]
...    ...    ...  .. ..  ..  ..    ...
9995  [한국]  [행과고]   1  1  29   1  [홍길동]
9996  [한국]  [행과고]   2  4   8   1  [홍길동]
9997  [한국]  [행과고]   1  4  17   2  [홍길동]
9998  [한국]  [행과고]   3  3  13   2  [홍길동]
9999  [한국]  [행과고]   1  3  15   1  [홍길동]

[10000 rows x 7 columns]

In [77]:
##흥미 부분 전처리

import numpy as np
#흥미 관련 문항 총 24개를 for문을 활용하여 각 응답에 알맞게 전처리 코딩 작업
for i in range(1,25):
    df_prepro[f'A{i}-1'] = np.where(df[f'A{i}'] == 1, 1, 0)
    df_prepro[f'A{i}-2'] = np.where(df[f'A{i}'] == 2, 1, 0)
    df_prepro[f'A{i}-3'] = np.where(df[f'A{i}'] == 3, 1, 0)
    df_prepro[f'A{i}-4'] = np.where(~df[f'A{i}'].isin([1, 2, 3]), 1, 0)
#성격 데이터 불러오기 및 직업환경 선호도 전처리
for n in range(1,31):
    df_prepro[f'B{n}'] = df[f'B{n}'].copy()
    df_prepro[f'D{n}-1'] = np.where(df[f'D{n}'] == 1,1,0)
    df_prepro[f'D{n}-2'] = np.where(df[f'D{n}'] == 2,1,0)
#적성 및 선호직업 불러오기
for w in range(1,61):
    df_prepro[f'C{w}'] = df[f'C{w}'].copy()
    df_prepro[f'E{w}'] = df[f'E{w}'].copy()

#1차 전처리 완료 데이터
df_prepro

,지역,학교명,학년,반,번호,성별,성명,A1-1,A1-2,A1-3,A1-4,A2-1,A2-2,A2-3,A2-4,A3-1,A3-2,A3-3,A3-4,A4-1,A4-2,A4-3,A4-4,A5-1,A5-2,A5-3,A5-4,A6-1,A6-2,A6-3,A6-4,A7-1,A7-2,A7-3,A7-4,A8-1,A8-2,A8-3,A8-4,A9-1,A9-2,A9-3,A9-4,A10-1,A10-2,A10-3,A10-4,A11-1,A11-2,A11-3,A11-4,A12-1,A12-2,A12-3,A12-4,A13-1,A13-2,A13-3,A13-4,A14-1,A14-2,A14-3,A14-4,A15-1,A15-2,A15-3,A15-4,A16-1,A16-2,A16-3,A16-4,A17-1,A17-2,A17-3,A17-4,A18-1,A18-2,A18-3,A18-4,A19-1,A19-2,A19-3,A19-4,A20-1,A20-2,A20-3,A20-4,A21-1,A21-2,A21-3,A21-4,A22-1,A22-2,A22-3,A22-4,A23-1,A23-2,A23-3,A23-4,A24-1,A24-2,A24-3,A24-4,B1,D1-1,D1-2,B2,D2-1,D2-2,B3,D3-1,D3-2,B4,D4-1,D4-2,B5,D5-1,D5-2,B6,D6-1,D6-2,B7,D7-1,D7-2,B8,D8-1,D8-2,B9,D9-1,D9-2,B10,D10-1,D10-2,B11,D11-1,D11-2,B12,D12-1,D12-2,B13,D13-1,D13-2,B14,D14-1,D14-2,B15,D15-1,D15-2,B16,D16-1,D16-2,B17,D17-1,D17-2,B18,D18-1,D18-2,B19,D19-1,D19-2,B20,D20-1,D20-2,B21,D21-1,D21-2,B22,D22-1,D22-2,B23,D23-1,D23-2,B24,D24-1,D24-2,B25,D25-1,D25-2,B26,D26-1,D26-2,B27,D27-1,D27-2,B28,D28-1,D28-2,B29,D29-1,D29-2,B30,D30-1,D30-2,C1,E1,C2,E2,C3,E3,C4,E4,C5,E5,C6,E6,C7,E7,C8,E8,C9,E9,C10,E10,C11,E11,C12,E12,C13,E13,C14,E14,C15,E15,C16,E16,C17,E17,C18,E18,C19,E19,C20,E20,C21,E21,C22,E22,C23,E23,C24,E24,C25,E25,C26,E26,C27,E27,C28,E28,C29,E29,C30,E30,C31,E31,C32,E32,C33,E33,C34,E34,C35,E35,C36,E36,C37,E37,C38,E38,C39,E39,C40,E40,C41,E41,C42,E42,C43,E43,C44,E44,C45,E45,C46,E46,C47,E47,C48,E48,C49,E49,C50,E50,C51,E51,C52,E52,C53,E53,C54,E54,C55,E55,C56,E56,C57,E57,C58,E58,C59,E59,C60,E60
0,[한국],[행과고],2,2,27,1,[홍길동],1,0,0,0,0,0,0,1,0,0,0,1,0,1,0,0,0,1,0,0,0,0,1,0,1,0,0,0,0,1,0,0,0,0,0,1,0,0,1,0,0,1,0,0,0,0,0,1,0,0,0,1,0,0,0,1,0,1,0,0,0,0,1,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,1,0,1,0,0,0,1,0,0,0,1,0,0,0,0,1,0,0,0,0,1,1,1,0,0,1,0,1,1,0,2,1,0,2,1,0,2,0,0,2,0,1,1,0,1,2,1,0,2,1,0,0,0,1,1,0,0,1,0,1,2,0,1,2,0,0,0,0,0,1,0,0,2,1,0,2,0,0,2,0,0,0,0,0,0,0,1,2,0,0,0,1,0,2,0,1,0,1,0,0,1,0,0,0,1,2,0,1,1,2,2,1,1,1,1,1,0,2,1,2,1,2,1,2,1,1,1,1,0,1,2,1,1,0,2,2,1,0,1,1,1,1,1,0,1,1,0,2,0,2,2,1,0,0,1,2,2,0,2,2,2,1,0,1,1,0,1,1,0,0,0,0,1,2,0,2,1,0,0,2,2,0,1,0,2,1,1,1,1,0,1,2,2,2,0,1,2,0,0,1,0,1,2,0,0,1,0,0,1,2,0,0,2,1,2,0,1,1,2,1,0,2,1,1,2,0,1,0
1,[한국],[행과고],3,5,17,2,[홍길동],1,0,0,0,0,1,0,0,0,1,0,0,1,0,0,0,0,0,0,1,0,0,1,0,0,0,1,0,0,1,0,0,0,0,1,0,1,0,0,0,0,0,0,1,1,0,0,0,1,0,0,0,0,0,0,1,0,1,0,0,0,0,0,1,0,0,0,1,0,0,1,0,0,1,0,0,0,1,0,0,0,0,0,1,0,0,1,0,0,0,0,1,0,0,1,0,0,0,1,0,1,0,1,0,0,1,0,1,1,1,0,1,1,0,1,0,0,0,0,1,0,0,1,2,0,1,2,1,0,1,1,0,2,0,1,1,0,1,2,0,1,2,0,1,0,0,0,1,0,1,0,0,1,1,0,1,1,0,0,0,0,1,1,0,1,0,0,0,1,0,1,1,0,0,1,0,0,0,0,1,2,0,1,2,0,0,2,0,0,0,1,1,2,0,1,0,2,2,2,1,0,0,1,0,2,0,0,1,2,1,0,2,2,1,2,2,2,2,2,2,2,1,0,2,2,2,0,2,2,2,0,1,2,2,2,0,2,2,0,2,2,2,2,0,0,2,1,0,0,1,0,1,0,2,0,2,0,0,2,0,2,0,2,0,0,1,1,1,0,2,2,0,1,0,2,2,0,1,0,1,1,0,2,2,1,0,2,1,0,1,1,1,1,2,0,2,0,2,2,2,1,1,0,1,1,2
2,[한국],[행과고],3,3,20,1,[홍길동],0,0,1,0,1,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,1,0,0,0,1,0,0,0,0,0,0,1,1,0,0,0,0,0,0,1,0,0,1,0,0,0,0,1,0,1,0,0,0,0,1,0,0,0,1,0,0,1,0,0,1,0,0,0,0,0,0,1,0,1,0,0,1,0,0,0,0,0,0,1,0,0,1,0,0,0,0,1,0,0,0,1,2,1,0,1,0,1,2,1,0,2,1,0,0,0,0,0,0,1,1,0,0,0,0,1,2,0,1,1,0,0,2,0,1,1,1,0,2,1,0,0,0,0,0,0,1,2,0,1,2,0,0,2,0,0,2,0,0,2,0,0,1,0,0,1,0,0,0,1,0,1,1,0,1,0,1,1,0,0,2,0,1,1,0,0,1,0,1,2,1,0,2,1,2,2,0,2,1,0,0,0,2,0,1,0,1,1,2,2,2,1,1,1,2,0,2,0,1,2,2,2,2,0,1,1,1,1,2,1,0,0,1,0,2,2,2,2,2,0,1,2,2,1,0,0,1,2,1,2,0,2,1,1,2,1,0,0,2,0,2,2,2,1,2,1,1,2,0,1,1,1,1,1,0,2,1,2,0,1,1,0,0,0,0,2,1,0,0,1,2,0,0,0,0,2,1,0,0,1,0,0,2,2,1,2,2,2,1,2,0,2
3,[한국],[행과고],2,3,9,2,[홍길동],0,0,1,0,0,0,1,0,1,0,0,0,1,0,0,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,0,1,0,0,0,1,0,1,0,0,0,0,1,0,0,0,1,0,0,1,0,0,0,1,0,0,0,0,0,1,0,1,0,0,0,0,0,1,0,0,0,1,0,1,0,0,0,1,0,0,0,1,0,0,0,1,0,0,1,0,0,0,0,0,1,0,2,0,0,1,1,0,2,0,0,0,1,0,1,0,0,0,1,0,0,1,0,1,0,1,0,0,0,1,0,1,1,1,0,2,0,1,1,0,0,1,0,0,0,1,0,0,0,1,1,1,0,2,1,0,0,1,0,2,0,1,2,0,0,2,0,0,0,0,1,1,0,0,2,0,1,1,1,0,1,0,1,2,0,1,0,0,0,0,0,1,0,0,0,0,2,1,0,0,0,0,0,1,0,2,1,1,2,0,0,2,1,2,2,2,2,2,0,1,1,1,1,1,0,1,1,1,0,0,2,1,2,0,2,0,1,2,2,0,0,1,2,1,2,2,1,2,0,1,1,0,1,1,0,0,1,0,1,0,0,2,1,0,2,2,1,2,0,2,0,2,0,2,2,2,1,0,0,0,2,1,2,2,1,2,1,2,0,0,0,1,1,1,2,2,2,2,0,1,0,2,2,2,2,2,2,0,1,2,0,2
4,[한국],[행과고],1,1,7,1,[홍길동],0,0,1,0,0,0,1,0,0,0,0,1,0,0,1,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,1,0,1,0,0,0,0,0,1,0,0,0,1,0,0,1,0,0,0,1,0,0,1,0,0,0,0,0,0,1,1,0,0,0,0,1,0,0,1,0,0,0,0,1,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,2,1,0,1,1,0,2,1,0,1,0,1,1,0,1,0,1,0,2,0,1,2,0,1,2,0,0,0,1,0,2,0,0,1,0,1,0,1,0,2,0,1,1,1,0,2,0,0,0,1,0,1,0,1,0,0,0,1,1,0,2,0,1,2,0,0,0,1,0,0,1,0,0,0,0,2,1,0,1,0,1,2,1,0,1,2,2,1,0,2,2,1,1,2,1,2,1,2,2,2,0,1,1,1,1,1,1,0,0,1,0,1,2,1,1,2,2,2,0,1,2,1,1,0,1,0,0,0,2,1,1,2,1,2,1,1,0,0,1,0,1,2,1,1,1,2,1,0,2,1,2,1,2,1,2,0,1,2,0,1,0,0,2,0,2,2,1,2,2,2,2,0,1,2,2,1,1,2,1,0,2,2,2,1,1,1,1,0,2,1,2,0,1,2,1,2,0,1,2,1,2,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,[한국],[행과고],1,1,29,1,[홍길동],0,1,0,0,0,1,0,0,0,1,0,0,1,0,0,0,0,1,0,0,1,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,0,1,0,0,0,1,0,0,1,0,0,0,0,0,0,1,0,0,1,0,1,0,0,0,0,0,0,1,0,1,0,0,1,0,0,0,0,0,1,0,1,0,0,0,0,1,0,0,0,1,0,0,1,0,0,0,0,0,1,0,0,0,2,0,1,2,1,0,1,1,0,2,0,1,1,1,0,1,0,1,2,0,1,2,0,1,2,0,0,1,0,1,2,0,0,0,1,0,0,1,0,2,0,1,1,0,1,1,0,0,0,0,0,1,0,0,1,0,0,0,0,1,2,0,0,1,0,0,1,1,0,2,0,1,1,0,1,0,0,1,0,0,1,1,0,1,1,1,1,2,2,1,0,2,2,0,0,2,1,1,2,0,1,1,2,0,1,0,1,1,2,0,2,0,2,2,2,1,2,0,2,0,0,0,2,2,1,1,1,1,0,2,2,2,0,1,2,1,2,1,1,0,1,2,0,0,2,0,0,2,1,0,1,0,1,2,1,1,1,0,0,2,1,1,2,1,1,0,1,1,0,0,1,1,2,2,2,1,2,1,0,2,2,1,1,1,1,2,2,2,2,2,0,0,0,0,1,2,2,1,0,1,2,2,1,2
9996,[한국],[행과고],2,4,8,1,[홍길동],0,0,1,0,1,0,0,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,0,1,0,0,1,0,0,0,1,0,0,0,0,1,1,0,0,0,0,1,0,0,1,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,0,0,0,1,0,0,1,0,1,0,0,0,0,0,1,0,0,0,1,0,0,0,1,0,1,0,0,0,2,0,1,2,0,0,0,1,0,0,0,0,0,0,0,1,0,0,2,0,1,1,1,0,0,1,0,2,0,0,1,0,0,1,0,1,1,1,0,0,0,1,2,0,0,1,1,0,1,1,0,1,1,0,0,0,1,2,0,1,1,0,1,0,0,1,1,1,0,0,1,0,1,1,0,1,1,0,1,0,0,2,0,1,1,1,0,2,0,1,1,2,2,0,0,2,0,1,2,1,1,1,0,1,2,0,1,2,2,0,2,0,2,1,1,2,1,0,2,1,2,0,1,2,0,0,1,2,2,1,0,2,2,2,0,2,2,1,1,1,0,1,1,2,1,2,0,2,1,2,0,0,1,0,1,0,0,2,2,0,1,0,0,0,2,0,2,1,1,2,0,1,0,0,2,1,1,0,2,1,0,1,0,0,2,1,0,1,1,0,2,1,0,1,2,0,0,1,1,2,0,0,2,0,2,1,2,0,2,1
9997,[한국],[행과고],1,4,17,2,[홍길동],1,0,0,0,0,0,0,1,0,0,1,0,0,0,1,0,0,0,0,1,1,0,0,0,0,0,1,0,1,0,0,0,0,0,1,0,1,0,0,0,0,1,0,0,0,0,0,1,0,0,1,0,1,0,0,0,0,1,0,0,0,0,0,1,0,0,1,0,0,1,0,0,1,0,0,0,0,0,0,1,0,0,1,0,0,0,0,1,0,1,0,0,0,0,1,0,0,0,1,2,1,0,1,0,1,1,1,0,1,0,1,1,0,0,1,0,0,0,0,1,0,1,0,0,0,0,0,1,0,1,0,0,1,0,0,2,0,0,0,0,1,1,1,0,2,1,0,0,0,0,2,0,0,2,0,0,2,1,0,0,0,0,2,1,0,1,0,1,1,1,0,2,0,0,1,1,0,0,0,0,0,0,0,0,1,0,2,2,0,2,2,1,0,2,0,0,1,1,1,1,1,0,0,0,2,0,2,0,2,2,1,1,0,1,0,0,1,1,1,0,0,0,1,2,1,1,2,2,1,0,0,2,0,1,2,1,1,2,0,0,1,1,2,0,2,1,0,0,1,0,2,2,0,2,1,0,2,0,0,1,1,0,0,0,2,0,1,1,2,2,1,2,0,1,1,2,1,1,0,2,2,2,0,2,1,1,2,0,2,0,0,0,1,1,1,1,2,0,0,2,2,0,1,0,0,0
9998,[한국],[행과고],3,3,13,2,[홍길동],1,0,0,0,1,0,0,0,0,1,0,0,0,1,0,0,0,0,0,1,0,0,1,0,0,1,0,0,0,0,0,1,0,0,1,0,1,0,0,0,0,1,0,0,1,0,0,0,0,0,1,0,0,1,0,0,0,0,0,1,1,0,0,0,0,0,1,0,1,0,0,0,0,0,0,1,0,0,1,0,0,0,1,0,0,1,0,0,0,0,0,1,0,0,1,0,0,0,1,1,0,0,0,0,0,1,0,1,2,0,1,2,1,0,2,0,0,2,0,1,2,1,0,0,0,0,1,1,0,0,1,0,1,1,0,2,0,1,1,0,0,0,1,0,1,1,0,1,1,0,1,0,1,1,1,0,0,0,1,2,0,0,0,0,1,2,1,0,2,1,0,0,0,0,1,0,1,2,0,0,0,0,0,1,0,1,1,2,0,0,0,0,2,1,1,0,0,0,1,0,0,0,2,0,1,0,0,0,2,2,0,1,1,2,0,0,1,1,1,2,2,0,0,2,1,0,2,1,1,0,0,0,2,1,0,2,2,0,0,1,2,2,0,0,1,0,0,2,0,2,2,1,2,1,2,0,1,0,0,1,1,1,1,1,1,0,0,0,1,2,0,1,0,0,0,2,0,0,0,0,2,0,1,0,0,1,1,0,2,0,2,1,1,1,2,1,1,1,0,1,1,0,2,2,1,1
9999,[한국],[행과고],1,3,15,1,[홍길동],0,1,0,0,0,0,0,1,0,1,0,0,0,0,1,0,1,0,0,0,0,0,0,1,1,0,0,0,0,1,0,0,0,1,0,0,1,0,0,0,0,1,0,0,1,0,0,0,1,0,0,0,0,1,0,0,0,1,0,0,0,0,1,0,0,0,0,1,1,0,0,0,0,0,1,0,1,0,0,0,0,0,0,1,1,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,1,0,1,0,1,0,1,2,0,0,2,0,1,1,0,0,2,0,0,1,0,1,1,0,1,1,0,0,1,0,0,0,0,0,1,0,1,2,1,0,1,0,0,2,0,1,1,0,0,0,1,0,2,0,0,2,1,0,2,0,1,2,0,0,2,0,0,1,0,0,2,0,1,1,0,1,2,1,0,2,0,1,0,0,1,1,0,2,2,2,0,2,0,0,2,1,0,1,1,0,1,2,0,1,2,2,0,0,1,1,1,0,0,1,2,1,2,1,1,0,0,1,2,0,1,1,0,1,2,0,2,0,2,0,2,1,0,1,1,1,1,2,2,2,1,0,1,0,2,0,2,0,0,2,1,2,0,2,2,2,0,0,2,0,0,1,2,2,2,1,1,0,1,1,2,0,0,0,0,2,2,1,2,0,2,0,0,2,0,2,0,1,1,1,2,1,1,0,1,1,0,1,1,0,2

In [78]:
#요인별 계산 데이터 프레임 생성
df_factor = df.iloc[:,0:7]
df_factor

        지역    학교명  학년  반  번호  성별     성명
0     [한국]  [행과고]   2  2  27   1  [홍길동]
1     [한국]  [행과고]   3  5  17   2  [홍길동]
2     [한국]  [행과고]   3  3  20   1  [홍길동]
3     [한국]  [행과고]   2  3   9   2  [홍길동]
4     [한국]  [행과고]   1  1   7   1  [홍길동]
...    ...    ...  .. ..  ..  ..    ...
9995  [한국]  [행과고]   1  1  29   1  [홍길동]
9996  [한국]  [행과고]   2  4   8   1  [홍길동]
9997  [한국]  [행과고]   1  4  17   2  [홍길동]
9998  [한국]  [행과고]   3  3  13   2  [홍길동]
9999  [한국]  [행과고]   1  3  15   1  [홍길동]

[10000 rows x 7 columns]

In [79]:
#흥미요인 계산
df_factor['interest_S'] = df_prepro[['A1-1', 'A4-4', 'A5-3', 'A6-2', 'A7-1', 'A10-4', 'A11-3', 'A12-2', 'A13-1', 'A16-4', 'A17-3', 'A18-2', 'A19-1', 'A22-4', 'A23-3', 'A24-2']].sum(axis=1)
df_factor['interest_E'] = df_prepro[['A1-2', 'A2-1', 'A5-4', 'A6-3', 'A7-2','A8-1', 'A11-4', 'A12-3', 'A13-2', 'A14-1', 'A17-4', 'A18-3', 'A19-2', 'A20-1', 'A23-4', 'A24-3' ]].sum(axis=1)
df_factor['interest_C'] = df_prepro[['A1-3', 'A2-2', 'A3-1', 'A6-4', 'A7-3', 'A8-2', 'A9-1', 'A12-4', 'A13-3', 'A14-2', 'A15-1', 'A18-4', 'A19-3', 'A20-2', 'A21-1', 'A24-4']].sum(axis=1)
df_factor['interest_R'] = df_prepro[['A1-4', 'A2-3', 'A3-2', 'A4-1', 'A7-4', 'A8-3', 'A9-2', 'A10-1', 'A13-4', 'A14-3', 'A15-2', 'A16-1', 'A19-4', 'A20-3', 'A21-2', 'A22-1']].sum(axis=1)
df_factor['interest_I'] = df_prepro[['A2-4', 'A3-3', 'A4-2', 'A5-1', 'A8-4', 'A9-3', 'A10-2', 'A11-1', 'A14-4', 'A15-3', 'A16-2', 'A17-1', 'A20-4', 'A21-3', 'A22-2', 'A23-1']].sum(axis=1)
df_factor['interest_A'] = df_prepro[['A3-4', 'A4-3', 'A5-2', 'A6-1', 'A9-4', 'A10-3', 'A11-2', 'A12-1', 'A15-4', 'A16-3', 'A17-2', 'A18-1', 'A21-4', 'A22-3', 'A23-2', 'A24-1']].sum(axis=1)

#성격요인 계산
df_factor['person_S'] = df_prepro[['B1','B7','B13','B19','B25']].sum(axis=1)
df_factor['person_E'] = df_prepro[['B2','B8','B14','B20','B26']].sum(axis=1)
df_factor['person_C'] = df_prepro[['B3','B9','B15','B21','B27']].sum(axis=1)
df_factor['person_R'] = df_prepro[['B4','B10','B16','B22','B28']].sum(axis=1)
df_factor['person_I'] = df_prepro[['B5','B11','B17','B23','B29']].sum(axis=1)
df_factor['person_A'] = df_prepro[['B6','B12','B18','B24','B30']].sum(axis=1)

#적성요인 계산
df_factor['apti_S'] = df_prepro[['C1', 'C7', 'C13', 'C19', 'C25', 'C31', 'C37', 'C43', 'C49', 'C55']].sum(axis=1)
df_factor['apti_E'] = df_prepro[['C2', 'C8', 'C14', 'C20', 'C26', 'C32', 'C38', 'C44', 'C50', 'C56']].sum(axis=1)
df_factor['apti_C'] = df_prepro[['C3', 'C9', 'C15', 'C21', 'C27', 'C33', 'C39', 'C45', 'C51', 'C57']].sum(axis=1)
df_factor['apti_R'] = df_prepro[['C4', 'C10', 'C16', 'C22', 'C28', 'C34', 'C40', 'C46', 'C52', 'C58']].sum(axis=1)
df_factor['apti_I'] = df_prepro[['C5', 'C11', 'C17', 'C23', 'C29', 'C35', 'C41', 'C47', 'C53', 'C59']].sum(axis=1)
df_factor['apti_A'] = df_prepro[['C6', 'C12', 'C18', 'C24', 'C30', 'C36', 'C42', 'C48', 'C54', 'C60']].sum(axis=1)

#직업환경요인 계산
df_factor['env_D'] = df_prepro[['D2-2', 'D4-1', 'D6-1', 'D8-1', 'D10-1', 'D12-2', 'D14-1', 'D16-2', 'D18-2', 'D20-1', 'D22-1', 'D24-2', 'D26-2', 'D28-1', 'D30-1']].sum(axis=1)
df_factor['env_I'] = df_prepro[['D2-1', 'D4-2', 'D6-2', 'D8-2', 'D10-2', 'D12-1', 'D14-2', 'D16-1', 'D18-1', 'D20-2', 'D22-2', 'D24-1', 'D26-1', 'D28-2', 'D30-2']].sum(axis=1)
df_factor['env_P'] = df_prepro[['D1-1', 'D3-1', 'D5-2', 'D7-1', 'D9-1', 'D11-2', 'D13-2', 'D15-1', 'D17-2', 'D19-1', 'D21-2', 'D23-1', 'D25-2', 'D27-1', 'D29-2']].sum(axis=1)
df_factor['env_T'] = df_prepro[['D1-2', 'D3-2', 'D5-1', 'D7-2', 'D9-2', 'D11-1', 'D13-1', 'D15-2', 'D17-1', 'D19-2', 'D21-1', 'D23-2', 'D25-1', 'D27-2', 'D29-1']].sum(axis=1)

#선호직업요인 계산
df_factor['job_S'] = df_prepro[['E1', 'E7', 'E13', 'E19', 'E25', 'E31', 'E37', 'E43', 'E49', 'E55']].sum(axis=1)
df_factor['job_E'] = df_prepro[['E2', 'E8', 'E14', 'E20', 'E26', 'E32', 'E38', 'E44', 'E50', 'E56']].sum(axis=1)
df_factor['job_C'] = df_prepro[['E3', 'E9', 'E15', 'E21', 'E27', 'E33', 'E39', 'E45', 'E51', 'E57']].sum(axis=1)
df_factor['job_R'] = df_prepro[['E4', 'E10', 'E16', 'E22', 'E28', 'E34', 'E40', 'E46', 'E52', 'E58']].sum(axis=1)
df_factor['job_I'] = df_prepro[['E5', 'E11', 'E17', 'E23', 'E29', 'E35', 'E41', 'E47', 'E53', 'E59']].sum(axis=1)
df_factor['job_A'] = df_prepro[['E6', 'E12', 'E18', 'E24', 'E30', 'E36', 'E42', 'E48', 'E54', 'E60']].sum(axis=1)

pd.set_option('display.max_columns', None)
df_factor

,지역,학교명,학년,반,번호,성별,성명,interest_S,interest_E,interest_C,interest_R,interest_I,interest_A,person_S,person_E,person_C,person_R,person_I,person_A,apti_S,apti_E,apti_C,apti_R,apti_I,apti_A,env_D,env_I,env_P,env_T,job_S,job_E,job_C,job_R,job_I,job_A
0,[한국],[행과고],2,2,27,1,[홍길동],3,2,3,5,4,7,5,8,5,5,4,7,11,10,11,7,8,12,6,4,4,7,9,11,12,10,6,10
1,[한국],[행과고],3,5,17,2,[홍길동],3,8,4,4,2,3,4,3,5,5,6,5,13,10,12,11,7,11,3,9,3,7,9,8,13,12,10,14
2,[한국],[행과고],3,3,20,1,[홍길동],4,5,6,1,5,3,8,4,7,7,5,6,12,13,7,13,10,10,4,4,6,4,9,12,9,10,13,9
3,[한국],[행과고],2,3,9,2,[홍길동],2,6,6,3,5,2,5,6,5,5,3,5,6,8,15,11,6,10,4,8,4,4,10,9,10,11,16,11
4,[한국],[행과고],1,1,7,1,[홍길동],6,3,7,3,3,2,3,2,4,8,8,7,12,12,7,14,16,11,6,6,4,6,18,9,9,7,14,9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,[한국],[행과고],1,1,29,1,[홍길동],5,3,3,5,3,5,4,4,6,6,6,6,9,12,15,13,14,8,5,6,4,6,4,13,12,9,11,11
9996,[한국],[행과고],2,4,8,1,[홍길동],5,4,4,3,5,3,6,6,4,5,4,5,7,12,13,10,11,11,2,9,4,7,12,2,12,12,8,8
9997,[한국],[행과고],1,4,17,2,[홍길동],6,4,3,2,5,4,5,8,4,2,5,3,9,8,9,12,8,12,3,3,4,7,13,8,9,7,5,10
9998,[한국],[행과고],3,3,13,2,[홍길동],2,6,2,5,5,4,6,6,4,5,4,6,5,6,8,13,8,13,2,8,3,8,12,7,7,5,5,7
9999,[한국],[행과고],1,3,15,1,[홍길동],2,3,4,5,2,8,2,7,6,7,9,6,9,6,8,9,11,10,3,6,5,3,14,10,10,7,11,11

In [80]:
df_factor.to_excel("C:\\Users\\user\\Desktop\\logic\\test.xlsx")

In [81]:
#규준 데이터 불러오기
interest_score = pd.read_excel("C:\\Users\\user\\Desktop\\logic\\score.xlsx",sheet_name="interest")
person_score = pd.read_excel("C:\\Users\\user\\Desktop\\logic\\score.xlsx",sheet_name="person")
apti_score = pd.read_excel("C:\\Users\\user\\Desktop\\logic\\score.xlsx",sheet_name="apti")
job_score = pd.read_excel("C:\\Users\\user\\Desktop\\logic\\score.xlsx",sheet_name="job")
env_p_t_score = pd.read_excel("C:\\Users\\user\\Desktop\\logic\\score.xlsx",sheet_name="env(p_t)")
env_d_i__score = pd.read_excel("C:\\Users\\user\\Desktop\\logic\\score.xlsx",sheet_name="env(d_i)")

In [82]:
df_factor.columns

Index(['지역', '학교명', '학년', '반', '번호', '성별', '성명', 'interest_S', 'interest_E',
       'interest_C', 'interest_R', 'interest_I', 'interest_A', 'person_S',
       'person_E', 'person_C', 'person_R', 'person_I', 'person_A', 'apti_S',
       'apti_E', 'apti_C', 'apti_R', 'apti_I', 'apti_A', 'env_D', 'env_I',
       'env_P', 'env_T', 'job_S', 'job_E', 'job_C', 'job_R', 'job_I', 'job_A'],
      dtype='object')

In [83]:
## T점수 작성하기

#흥미 T점수
df_factor['interest_S_T'] = np.where(
    df_factor['성별'] == 1,
    df_factor['interest_S'].map(dict(zip(interest_score['score'], interest_score['T_score_m']))),
    df_factor['interest_S'].map(dict(zip(interest_score['score'], interest_score['T_score_f'])))
)

df_factor['interest_E_T'] = np.where(
    df_factor['성별'] == 1,
    df_factor['interest_E'].map(dict(zip(interest_score['score'], interest_score['T_score_m']))),
    df_factor['interest_E'].map(dict(zip(interest_score['score'], interest_score['T_score_f'])))
)

df_factor['interest_C_T'] = np.where(
    df_factor['성별'] == 1,
    df_factor['interest_C'].map(dict(zip(interest_score['score'], interest_score['T_score_m']))),
    df_factor['interest_C'].map(dict(zip(interest_score['score'], interest_score['T_score_f'])))
)

df_factor['interest_R_T'] = np.where(
    df_factor['성별'] == 1,
    df_factor['interest_R'].map(dict(zip(interest_score['score'], interest_score['T_score_m']))),
    df_factor['interest_R'].map(dict(zip(interest_score['score'], interest_score['T_score_f'])))
)

df_factor['interest_I_T'] = np.where(
    df_factor['성별'] == 1,
    df_factor['interest_I'].map(dict(zip(interest_score['score'], interest_score['T_score_m']))),
    df_factor['interest_I'].map(dict(zip(interest_score['score'], interest_score['T_score_f'])))
)

df_factor['interest_A_T'] = np.where(
    df_factor['성별'] == 1,
    df_factor['interest_A'].map(dict(zip(interest_score['score'], interest_score['T_score_m']))),
    df_factor['interest_A'].map(dict(zip(interest_score['score'], interest_score['T_score_f'])))
)

#성격 T점수
df_factor['person_S_T'] = np.where(
    df_factor['성별'] == 1,
    df_factor['person_S'].map(dict(zip(person_score['score'], person_score['T_score_m']))),
    df_factor['person_S'].map(dict(zip(person_score['score'], person_score['T_score_f'])))
)

df_factor['person_E_T'] = np.where(
    df_factor['성별'] == 1,
    df_factor['person_E'].map(dict(zip(person_score['score'], person_score['T_score_m']))),
    df_factor['person_E'].map(dict(zip(person_score['score'], person_score['T_score_f'])))
)

df_factor['person_C_T'] = np.where(
    df_factor['성별'] == 1,
    df_factor['person_C'].map(dict(zip(person_score['score'], person_score['T_score_m']))),
    df_factor['person_C'].map(dict(zip(person_score['score'], person_score['T_score_f'])))
)

df_factor['person_R_T'] = np.where(
    df_factor['성별'] == 1,
    df_factor['person_R'].map(dict(zip(person_score['score'], person_score['T_score_m']))),
    df_factor['person_R'].map(dict(zip(person_score['score'], person_score['T_score_f'])))
)

df_factor['person_I_T'] = np.where(
    df_factor['성별'] == 1,
    df_factor['person_I'].map(dict(zip(person_score['score'], person_score['T_score_m']))),
    df_factor['person_I'].map(dict(zip(person_score['score'], person_score['T_score_f'])))
)

df_factor['person_A_T'] = np.where(
    df_factor['성별'] == 1,
    df_factor['person_A'].map(dict(zip(person_score['score'], person_score['T_score_m']))),
    df_factor['person_A'].map(dict(zip(person_score['score'], person_score['T_score_f'])))
)

#적성 T점수
df_factor['apti_S_T'] = np.where(
    df_factor['성별'] == 1,
    df_factor['apti_S'].map(dict(zip(apti_score['score'], apti_score['T_score_m']))),
    df_factor['apti_S'].map(dict(zip(apti_score['score'], apti_score['T_score_f'])))
)

df_factor['apti_E_T'] = np.where(
    df_factor['성별'] == 1,
    df_factor['apti_E'].map(dict(zip(apti_score['score'], apti_score['T_score_m']))),
    df_factor['apti_E'].map(dict(zip(apti_score['score'], apti_score['T_score_f'])))
)

df_factor['apti_C_T'] = np.where(
    df_factor['성별'] == 1,
    df_factor['apti_C'].map(dict(zip(apti_score['score'], apti_score['T_score_m']))),
    df_factor['apti_C'].map(dict(zip(apti_score['score'], apti_score['T_score_f'])))
)

df_factor['apti_R_T'] = np.where(
    df_factor['성별'] == 1,
    df_factor['apti_R'].map(dict(zip(apti_score['score'], apti_score['T_score_m']))),
    df_factor['apti_R'].map(dict(zip(apti_score['score'], apti_score['T_score_f'])))
)

df_factor['apti_I_T'] = np.where(
    df_factor['성별'] == 1,
    df_factor['apti_I'].map(dict(zip(apti_score['score'], apti_score['T_score_m']))),
    df_factor['apti_I'].map(dict(zip(apti_score['score'], apti_score['T_score_f'])))
)

df_factor['apti_A_T'] = np.where(
    df_factor['성별'] == 1,
    df_factor['apti_A'].map(dict(zip(apti_score['score'], apti_score['T_score_m']))),
    df_factor['apti_A'].map(dict(zip(apti_score['score'], apti_score['T_score_f'])))
)

#선호직업 T점수
df_factor['job_S_T'] = np.where(
    df_factor['성별'] == 1,
    df_factor['job_S'].map(dict(zip(job_score['score'], job_score['T_score_m']))),
    df_factor['job_S'].map(dict(zip(job_score['score'], job_score['T_score_f'])))
)

df_factor['job_E_T'] = np.where(
    df_factor['성별'] == 1,
    df_factor['job_E'].map(dict(zip(job_score['score'], job_score['T_score_m']))),
    df_factor['job_E'].map(dict(zip(job_score['score'], job_score['T_score_f'])))
)

df_factor['job_C_T'] = np.where(
    df_factor['성별'] == 1,
    df_factor['job_C'].map(dict(zip(job_score['score'], job_score['T_score_m']))),
    df_factor['job_C'].map(dict(zip(job_score['score'], job_score['T_score_f'])))
)

df_factor['job_R_T'] = np.where(
    df_factor['성별'] == 1,
    df_factor['job_R'].map(dict(zip(job_score['score'], job_score['T_score_m']))),
    df_factor['job_R'].map(dict(zip(job_score['score'], job_score['T_score_f'])))
)

df_factor['job_I_T'] = np.where(
    df_factor['성별'] == 1,
    df_factor['job_I'].map(dict(zip(job_score['score'], job_score['T_score_m']))),
    df_factor['job_I'].map(dict(zip(job_score['score'], job_score['T_score_f'])))
)

df_factor['job_A_T'] = np.where(
    df_factor['성별'] == 1,
    df_factor['job_A'].map(dict(zip(job_score['score'], job_score['T_score_m']))),
    df_factor['job_A'].map(dict(zip(job_score['score'], job_score['T_score_f'])))
)

#직업환경 T점수
df_factor['env_D_T'] = np.where(
    df_factor['성별'] == 1,
    df_factor['env_D'].map(dict(zip(env_d_i__score['score'],env_d_i__score['T_score_m']))),
    df_factor['env_D'].map(dict(zip(env_d_i__score['score'],env_d_i__score['T_score_f'])))
)

df_factor['env_I_T'] = np.where(
    df_factor['성별'] == 1,
    df_factor['env_I'].map(dict(zip(env_d_i__score['score'],env_d_i__score['T_score_m']))),
    df_factor['env_I'].map(dict(zip(env_d_i__score['score'],env_d_i__score['T_score_f'])))
)

df_factor['env_P_T'] = np.where(
    df_factor['성별'] == 1,
    df_factor['env_P'].map(dict(zip(env_p_t_score['score'],env_p_t_score['T_score_m']))),
    df_factor['env_P'].map(dict(zip(env_p_t_score['score'],env_p_t_score['T_score_f'])))
)

df_factor['env_T_T'] = np.where(
    df_factor['성별'] == 1,
    df_factor['env_T'].map(dict(zip(env_p_t_score['score'],env_p_t_score['T_score_m']))),
    df_factor['env_T'].map(dict(zip(env_p_t_score['score'],env_p_t_score['T_score_f'])))
)

df_factor

,지역,학교명,학년,반,번호,성별,성명,interest_S,interest_E,interest_C,interest_R,interest_I,interest_A,person_S,person_E,person_C,person_R,person_I,person_A,apti_S,apti_E,apti_C,apti_R,apti_I,apti_A,env_D,env_I,env_P,env_T,job_S,job_E,job_C,job_R,job_I,job_A,interest_S_T,interest_E_T,interest_C_T,interest_R_T,interest_I_T,interest_A_T,person_S_T,person_E_T,person_C_T,person_R_T,person_I_T,person_A_T,apti_S_T,apti_E_T,apti_C_T,apti_R_T,apti_I_T,apti_A_T,job_S_T,job_E_T,job_C_T,job_R_T,job_I_T,job_A_T,env_D_T,env_I_T,env_P_T,env_T_T
0,[한국],[행과고],2,2,27,1,[홍길동],3,2,3,5,4,7,5,8,5,5,4,7,11,10,11,7,8,12,6,4,4,7,9,11,12,10,6,10,35,30,35,45,40,53,50,65,50,50,45,60,54,51,54,43,46,57,48,52,55,50,41,50,49,43,42,50
1,[한국],[행과고],3,5,17,2,[홍길동],3,8,4,4,2,3,4,3,5,5,6,5,13,10,12,11,7,11,3,9,3,7,9,8,13,12,10,14,34,54,38,38,30,34,44,39,49,49,55,49,59,50,56,53,43,53,49,47,59,56,51,62,40,59,39,51
2,[한국],[행과고],3,3,20,1,[홍길동],4,5,6,1,5,3,8,4,7,7,5,6,12,13,7,13,10,10,4,4,6,4,9,12,9,10,13,9,40,45,49,25,45,35,65,45,60,60,50,55,57,60,43,60,51,51,48,55,48,50,58,48,43,43,47,42
3,[한국],[행과고],2,3,9,2,[홍길동],2,6,6,3,5,2,5,6,5,5,3,5,6,8,15,11,6,10,4,8,4,4,10,9,10,11,16,11,30,46,46,34,42,30,49,55,49,49,39,49,40,45,65,53,40,50,51,49,51,53,67,53,44,56,42,42
4,[한국],[행과고],1,1,7,1,[홍길동],6,3,7,3,3,2,3,2,4,8,8,7,12,12,7,14,16,11,6,6,4,6,18,9,9,7,14,9,49,35,53,35,35,30,39,34,45,65,65,60,57,57,43,63,69,54,73,48,48,43,61,48,49,49,42,47
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,[한국],[행과고],1,1,29,1,[홍길동],5,3,3,5,3,5,4,4,6,6,6,6,9,12,15,13,14,8,5,6,4,6,4,13,12,9,11,11,45,35,35,45,35,45,45,45,55,55,55,55,48,57,66,60,63,46,36,58,55,48,52,52,46,49,42,47
9996,[한국],[행과고],2,4,8,1,[홍길동],5,4,4,3,5,3,6,6,4,5,4,5,7,12,13,10,11,11,2,9,4,7,12,2,12,12,8,8,45,40,40,35,45,35,55,55,45,50,45,50,43,57,60,51,54,54,55,30,55,55,46,46,35,58,42,50
9997,[한국],[행과고],1,4,17,2,[홍길동],6,4,3,2,5,4,5,8,4,2,5,3,9,8,9,12,8,12,3,3,4,7,13,8,9,7,5,10,46,38,34,30,42,38,49,65,44,34,49,39,48,45,48,56,45,56,59,47,49,44,39,51,40,40,42,51
9998,[한국],[행과고],3,3,13,2,[홍길동],2,6,2,5,5,4,6,6,4,5,4,6,5,6,8,13,8,13,2,8,3,8,12,7,7,5,5,7,30,46,30,42,42,38,55,55,44,49,44,55,37,40,45,59,45,59,56,44,44,39,39,44,35,56,39,54
9999,[한국],[행과고],1,3,15,1,[홍길동],2,3,4,5,2,8,2,7,6,7,9,6,9,6,8,9,11,10,3,6,5,3,14,10,10,7,11,11,30,35,40,45,30,57,34,60,55,60,70,55,48,41,46,48,54,51,61,50,50,43,52,52,39,49,45,39

In [84]:
df_factor.to_excel("C:\\Users\\user\\Desktop\\logic\\test.xlsx")

In [85]:
df_factor['factor_S'] = ((df_factor['interest_S_T']*2) + df_factor['person_S_T'] + (df_factor['apti_S_T']*2) + df_factor['job_S_T'])/6
df_factor['factor_E'] = ((df_factor['interest_E_T']*2) + df_factor['person_E_T'] + (df_factor['apti_E_T']*2) + df_factor['job_E_T'])/6
df_factor['factor_C'] = ((df_factor['interest_C_T']*2) + df_factor['person_C_T'] + (df_factor['apti_C_T']*2) + df_factor['job_C_T'])/6
df_factor['factor_R'] = ((df_factor['interest_R_T']*2) + df_factor['person_R_T'] + (df_factor['apti_R_T']*2) + df_factor['job_R_T'])/6
df_factor['factor_I'] = ((df_factor['interest_I_T']*2) + df_factor['person_I_T'] + (df_factor['apti_I_T']*2) + df_factor['job_I_T'])/6
df_factor['factor_A'] = ((df_factor['interest_A_T']*2) + df_factor['person_A_T'] + (df_factor['apti_A_T']*2) + df_factor['job_A_T'])/6

df_factor

,지역,학교명,학년,반,번호,성별,성명,interest_S,interest_E,interest_C,interest_R,interest_I,interest_A,person_S,person_E,person_C,person_R,person_I,person_A,apti_S,apti_E,apti_C,apti_R,apti_I,apti_A,env_D,env_I,env_P,env_T,job_S,job_E,job_C,job_R,job_I,job_A,interest_S_T,interest_E_T,interest_C_T,interest_R_T,interest_I_T,interest_A_T,person_S_T,person_E_T,person_C_T,person_R_T,person_I_T,person_A_T,apti_S_T,apti_E_T,apti_C_T,apti_R_T,apti_I_T,apti_A_T,job_S_T,job_E_T,job_C_T,job_R_T,job_I_T,job_A_T,env_D_T,env_I_T,env_P_T,env_T_T,factor_S,factor_E,factor_C,factor_R,factor_I,factor_A
0,[한국],[행과고],2,2,27,1,[홍길동],3,2,3,5,4,7,5,8,5,5,4,7,11,10,11,7,8,12,6,4,4,7,9,11,12,10,6,10,35,30,35,45,40,53,50,65,50,50,45,60,54,51,54,43,46,57,48,52,55,50,41,50,49,43,42,50,46.000000,46.500000,47.166667,46.000000,43.000000,55.000000
1,[한국],[행과고],3,5,17,2,[홍길동],3,8,4,4,2,3,4,3,5,5,6,5,13,10,12,11,7,11,3,9,3,7,9,8,13,12,10,14,34,54,38,38,30,34,44,39,49,49,55,49,59,50,56,53,43,53,49,47,59,56,51,62,40,59,39,51,46.500000,49.000000,49.333333,47.833333,42.000000,47.500000
2,[한국],[행과고],3,3,20,1,[홍길동],4,5,6,1,5,3,8,4,7,7,5,6,12,13,7,13,10,10,4,4,6,4,9,12,9,10,13,9,40,45,49,25,45,35,65,45,60,60,50,55,57,60,43,60,51,51,48,55,48,50,58,48,43,43,47,42,51.166667,51.666667,48.666667,46.666667,50.000000,45.833333
3,[한국],[행과고],2,3,9,2,[홍길동],2,6,6,3,5,2,5,6,5,5,3,5,6,8,15,11,6,10,4,8,4,4,10,9,10,11,16,11,30,46,46,34,42,30,49,55,49,49,39,49,40,45,65,53,40,50,51,49,51,53,67,53,44,56,42,42,40.000000,47.666667,53.666667,46.000000,45.000000,43.666667
4,[한국],[행과고],1,1,7,1,[홍길동],6,3,7,3,3,2,3,2,4,8,8,7,12,12,7,14,16,11,6,6,4,6,18,9,9,7,14,9,49,35,53,35,35,30,39,34,45,65,65,60,57,57,43,63,69,54,73,48,48,43,61,48,49,49,42,47,54.000000,44.333333,47.500000,50.666667,55.666667,46.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,[한국],[행과고],1,1,29,1,[홍길동],5,3,3,5,3,5,4,4,6,6,6,6,9,12,15,13,14,8,5,6,4,6,4,13,12,9,11,11,45,35,35,45,35,45,45,45,55,55,55,55,48,57,66,60,63,46,36,58,55,48,52,52,46,49,42,47,44.500000,47.833333,52.000000,52.166667,50.500000,48.166667
9996,[한국],[행과고],2,4,8,1,[홍길동],5,4,4,3,5,3,6,6,4,5,4,5,7,12,13,10,11,11,2,9,4,7,12,2,12,12,8,8,45,40,40,35,45,35,55,55,45,50,45,50,43,57,60,51,54,54,55,30,55,55,46,46,35,58,42,50,47.666667,46.500000,50.000000,46.166667,48.166667,45.666667
9997,[한국],[행과고],1,4,17,2,[홍길동],6,4,3,2,5,4,5,8,4,2,5,3,9,8,9,12,8,12,3,3,4,7,13,8,9,7,5,10,46,38,34,30,42,38,49,65,44,34,49,39,48,45,48,56,45,56,59,47,49,44,39,51,40,40,42,51,49.333333,46.333333,42.833333,41.666667,43.666667,46.333333
9998,[한국],[행과고],3,3,13,2,[홍길동],2,6,2,5,5,4,6,6,4,5,4,6,5,6,8,13,8,13,2,8,3,8,12,7,7,5,5,7,30,46,30,42,42,38,55,55,44,49,44,55,37,40,45,59,45,59,56,44,44,39,39,44,35,56,39,54,40.833333,45.166667,39.666667,48.333333,42.833333,48.833333
9999,[한국],[행과고],1,3,15,1,[홍길동],2,3,4,5,2,8,2,7,6,7,9,6,9,6,8,9,11,10,3,6,5,3,14,10,10,7,11,11,30,35,40,45,30,57,34,60,55,60,70,55,48,41,46,48,54,51,61,50,50,43,52,52,39,49,45,39,41.833333,43.666667,46.166667,48.166667,48.333333,53.833333

In [86]:
factor_columns = ['factor_S', 'factor_E', 'factor_C', 'factor_R', 'factor_I', 'factor_A']
factor_labels = ['S', 'E', 'C', 'R', 'I', 'A']

def get_rank(row, factor_labels):
    """동점을 고려하여 순위를 결정하는 함수."""
    scores = row.values
    sorted_indices = np.argsort(-scores)  # 큰 순서대로 정렬
    sorted_labels = [factor_labels[i] for i in sorted_indices]
    sorted_scores = scores[sorted_indices]
    return sorted_labels, sorted_scores

# 순위 계산
df_factor[['순위_labels', '순위_scores']] = df_factor[factor_columns].apply(
    lambda row: get_rank(row, factor_labels), axis=1, result_type='expand'
)

# 각 순위 및 점수 컬럼 추가
for rank in range(1, 7):  # 1순위부터 6순위까지
    df_factor[f'{rank}순위'] = df_factor['순위_labels'].apply(lambda x: x[rank - 1])
    df_factor[f'{rank}순위_점수'] = df_factor['순위_scores'].apply(lambda x: x[rank - 1])

# 결과에서 임시 컬럼 제거
df_factor.drop(['순위_labels', '순위_scores'], axis=1, inplace=True)
df_factor

,지역,학교명,학년,반,번호,성별,성명,interest_S,interest_E,interest_C,interest_R,interest_I,interest_A,person_S,person_E,person_C,person_R,person_I,person_A,apti_S,apti_E,apti_C,apti_R,apti_I,apti_A,env_D,env_I,env_P,env_T,job_S,job_E,job_C,job_R,job_I,job_A,interest_S_T,interest_E_T,interest_C_T,interest_R_T,interest_I_T,interest_A_T,person_S_T,person_E_T,person_C_T,person_R_T,person_I_T,person_A_T,apti_S_T,apti_E_T,apti_C_T,apti_R_T,apti_I_T,apti_A_T,job_S_T,job_E_T,job_C_T,job_R_T,job_I_T,job_A_T,env_D_T,env_I_T,env_P_T,env_T_T,factor_S,factor_E,factor_C,factor_R,factor_I,factor_A,1순위,1순위_점수,2순위,2순위_점수,3순위,3순위_점수,4순위,4순위_점수,5순위,5순위_점수,6순위,6순위_점수
0,[한국],[행과고],2,2,27,1,[홍길동],3,2,3,5,4,7,5,8,5,5,4,7,11,10,11,7,8,12,6,4,4,7,9,11,12,10,6,10,35,30,35,45,40,53,50,65,50,50,45,60,54,51,54,43,46,57,48,52,55,50,41,50,49,43,42,50,46.000000,46.500000,47.166667,46.000000,43.000000,55.000000,A,55.000000,C,47.166667,E,46.500000,S,46.000000,R,46.000000,I,43.000000
1,[한국],[행과고],3,5,17,2,[홍길동],3,8,4,4,2,3,4,3,5,5,6,5,13,10,12,11,7,11,3,9,3,7,9,8,13,12,10,14,34,54,38,38,30,34,44,39,49,49,55,49,59,50,56,53,43,53,49,47,59,56,51,62,40,59,39,51,46.500000,49.000000,49.333333,47.833333,42.000000,47.500000,C,49.333333,E,49.000000,R,47.833333,A,47.500000,S,46.500000,I,42.000000
2,[한국],[행과고],3,3,20,1,[홍길동],4,5,6,1,5,3,8,4,7,7,5,6,12,13,7,13,10,10,4,4,6,4,9,12,9,10,13,9,40,45,49,25,45,35,65,45,60,60,50,55,57,60,43,60,51,51,48,55,48,50,58,48,43,43,47,42,51.166667,51.666667,48.666667,46.666667,50.000000,45.833333,E,51.666667,S,51.166667,I,50.000000,C,48.666667,R,46.666667,A,45.833333
3,[한국],[행과고],2,3,9,2,[홍길동],2,6,6,3,5,2,5,6,5,5,3,5,6,8,15,11,6,10,4,8,4,4,10,9,10,11,16,11,30,46,46,34,42,30,49,55,49,49,39,49,40,45,65,53,40,50,51,49,51,53,67,53,44,56,42,42,40.000000,47.666667,53.666667,46.000000,45.000000,43.666667,C,53.666667,E,47.666667,R,46.000000,I,45.000000,A,43.666667,S,40.000000
4,[한국],[행과고],1,1,7,1,[홍길동],6,3,7,3,3,2,3,2,4,8,8,7,12,12,7,14,16,11,6,6,4,6,18,9,9,7,14,9,49,35,53,35,35,30,39,34,45,65,65,60,57,57,43,63,69,54,73,48,48,43,61,48,49,49,42,47,54.000000,44.333333,47.500000,50.666667,55.666667,46.000000,I,55.666667,S,54.000000,R,50.666667,C,47.500000,A,46.000000,E,44.333333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,[한국],[행과고],1,1,29,1,[홍길동],5,3,3,5,3,5,4,4,6,6,6,6,9,12,15,13,14,8,5,6,4,6,4,13,12,9,11,11,45,35,35,45,35,45,45,45,55,55,55,55,48,57,66,60,63,46,36,58,55,48,52,52,46,49,42,47,44.500000,47.833333,52.000000,52.166667,50.500000,48.166667,R,52.166667,C,52.000000,I,50.500000,A,48.166667,E,47.833333,S,44.500000
9996,[한국],[행과고],2,4,8,1,[홍길동],5,4,4,3,5,3,6,6,4,5,4,5,7,12,13,10,11,11,2,9,4,7,12,2,12,12,8,8,45,40,40,35,45,35,55,55,45,50,45,50,43,57,60,51,54,54,55,30,55,55,46,46,35,58,42,50,47.666667,46.500000,50.000000,46.166667,48.166667,45.666667,C,50.000000,I,48.166667,S,47.666667,E,46.500000,R,46.166667,A,45.666667
9997,[한국],[행과고],1,4,17,2,[홍길동],6,4,3,2,5,4,5,8,4,2,5,3,9,8,9,12,8,12,3,3,4,7,13,8,9,7,5,10,46,38,34,30,42,38,49,65,44,34,49,39,48,45,48,56,45,56,59,47,49,44,39,51,40,40,42,51,49.333333,46.333333,42.833333,41.666667,43.666667,46.333333,S,49.333333,E,46.333333,A,46.333333,I,43.666667,C,42.833333,R,41.666667
9998,[한국],[행과고],3,3,13,2,[홍길동],2,6,2,5,5,4,6,6,4,5,4,6,5,6,8,13,8,13,2,8,3,8,12,7,7,5,5,7,30,46,30,42,42,38,55,55,44,49,44,55,37,40,45,59,45,59,56,44,44,39,39,44,35,56,39,54,40.833333,45.166667,39.666667,48.333333,42.833333,48.833333,A,48.833333,R,48.333333,E,45.166667,I,42.833333,S,40.833333,C,39.666667
9999,[한국],[행과고],1,3,15,1,[홍길동],2,3,4,5,2,8,2,7,6,7,9,6,9,6,8,9,11,10,3,6,5,3,14,10,10,7,11,11,30,35,40,45,30,57,34,60,55,60,70,55,48,41,46,48,54,51,61,50,50,43,52,52,39,49,45,39,41.833333,43.666667,46.166667,48.166667,48.333333,53.833333,A,53.833333,I,48.333333,R,48.166667,C,46.166667,E,43.666667,S,41.833333

In [87]:
df_count = df.iloc[:,8:]
df_count.notnull().sum(axis=1)

df_factor['반응적합'] = (df_count.notnull().sum(axis=1)/204)*100

df_factor

,지역,학교명,학년,반,번호,성별,성명,interest_S,interest_E,interest_C,interest_R,interest_I,interest_A,person_S,person_E,person_C,person_R,person_I,person_A,apti_S,apti_E,apti_C,apti_R,apti_I,apti_A,env_D,env_I,env_P,env_T,job_S,job_E,job_C,job_R,job_I,job_A,interest_S_T,interest_E_T,interest_C_T,interest_R_T,interest_I_T,interest_A_T,person_S_T,person_E_T,person_C_T,person_R_T,person_I_T,person_A_T,apti_S_T,apti_E_T,apti_C_T,apti_R_T,apti_I_T,apti_A_T,job_S_T,job_E_T,job_C_T,job_R_T,job_I_T,job_A_T,env_D_T,env_I_T,env_P_T,env_T_T,factor_S,factor_E,factor_C,factor_R,factor_I,factor_A,1순위,1순위_점수,2순위,2순위_점수,3순위,3순위_점수,4순위,4순위_점수,5순위,5순위_점수,6순위,6순위_점수,반응적합
0,[한국],[행과고],2,2,27,1,[홍길동],3,2,3,5,4,7,5,8,5,5,4,7,11,10,11,7,8,12,6,4,4,7,9,11,12,10,6,10,35,30,35,45,40,53,50,65,50,50,45,60,54,51,54,43,46,57,48,52,55,50,41,50,49,43,42,50,46.000000,46.500000,47.166667,46.000000,43.000000,55.000000,A,55.000000,C,47.166667,E,46.500000,S,46.000000,R,46.000000,I,43.000000,100.0
1,[한국],[행과고],3,5,17,2,[홍길동],3,8,4,4,2,3,4,3,5,5,6,5,13,10,12,11,7,11,3,9,3,7,9,8,13,12,10,14,34,54,38,38,30,34,44,39,49,49,55,49,59,50,56,53,43,53,49,47,59,56,51,62,40,59,39,51,46.500000,49.000000,49.333333,47.833333,42.000000,47.500000,C,49.333333,E,49.000000,R,47.833333,A,47.500000,S,46.500000,I,42.000000,100.0
2,[한국],[행과고],3,3,20,1,[홍길동],4,5,6,1,5,3,8,4,7,7,5,6,12,13,7,13,10,10,4,4,6,4,9,12,9,10,13,9,40,45,49,25,45,35,65,45,60,60,50,55,57,60,43,60,51,51,48,55,48,50,58,48,43,43,47,42,51.166667,51.666667,48.666667,46.666667,50.000000,45.833333,E,51.666667,S,51.166667,I,50.000000,C,48.666667,R,46.666667,A,45.833333,100.0
3,[한국],[행과고],2,3,9,2,[홍길동],2,6,6,3,5,2,5,6,5,5,3,5,6,8,15,11,6,10,4,8,4,4,10,9,10,11,16,11,30,46,46,34,42,30,49,55,49,49,39,49,40,45,65,53,40,50,51,49,51,53,67,53,44,56,42,42,40.000000,47.666667,53.666667,46.000000,45.000000,43.666667,C,53.666667,E,47.666667,R,46.000000,I,45.000000,A,43.666667,S,40.000000,100.0
4,[한국],[행과고],1,1,7,1,[홍길동],6,3,7,3,3,2,3,2,4,8,8,7,12,12,7,14,16,11,6,6,4,6,18,9,9,7,14,9,49,35,53,35,35,30,39,34,45,65,65,60,57,57,43,63,69,54,73,48,48,43,61,48,49,49,42,47,54.000000,44.333333,47.500000,50.666667,55.666667,46.000000,I,55.666667,S,54.000000,R,50.666667,C,47.500000,A,46.000000,E,44.333333,100.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,[한국],[행과고],1,1,29,1,[홍길동],5,3,3,5,3,5,4,4,6,6,6,6,9,12,15,13,14,8,5,6,4,6,4,13,12,9,11,11,45,35,35,45,35,45,45,45,55,55,55,55,48,57,66,60,63,46,36,58,55,48,52,52,46,49,42,47,44.500000,47.833333,52.000000,52.166667,50.500000,48.166667,R,52.166667,C,52.000000,I,50.500000,A,48.166667,E,47.833333,S,44.500000,100.0
9996,[한국],[행과고],2,4,8,1,[홍길동],5,4,4,3,5,3,6,6,4,5,4,5,7,12,13,10,11,11,2,9,4,7,12,2,12,12,8,8,45,40,40,35,45,35,55,55,45,50,45,50,43,57,60,51,54,54,55,30,55,55,46,46,35,58,42,50,47.666667,46.500000,50.000000,46.166667,48.166667,45.666667,C,50.000000,I,48.166667,S,47.666667,E,46.500000,R,46.166667,A,45.666667,100.0
9997,[한국],[행과고],1,4,17,2,[홍길동],6,4,3,2,5,4,5,8,4,2,5,3,9,8,9,12,8,12,3,3,4,7,13,8,9,7,5,10,46,38,34,30,42,38,49,65,44,34,49,39,48,45,48,56,45,56,59,47,49,44,39,51,40,40,42,51,49.333333,46.333333,42.833333,41.666667,43.666667,46.333333,S,49.333333,E,46.333333,A,46.333333,I,43.666667,C,42.833333,R,41.666667,100.0
9998,[한국],[행과고],3,3,13,2,[홍길동],2,6,2,5,5,4,6,6,4,5,4,6,5,6,8,13,8,13,2,8,3,8,12,7,7,5,5,7,30,46,30,42,42,38,55,55,44,49,44,55,37,40,45,59,45,59,56,44,44,39,39,44,35,56,39,54,40.833333,45.166667,39.666667,48.333333,42.833333,48.833333,A,48.833333,R,48.333333,E,45.166667,I,42.833333,S,40.833333,C,39.666667,100.0
9999,[한국],[행과고],1,3,15,1,[홍길동],2,3,4,5,2,8,2,7,6,7,9,6,9,6,8,9,11,10,3,6,5,3,14,10,10,7,11,11,30,35,40,45,30,57,34,60,55,60,70,55,48,41,46,48,54,51,61,50,50,43,52,52,39,49,45,39,41.833333,43.666667,46.166667,48.166667,48.333333,53.833333,A,53.833333,I,48.333333,R,48.166667,C,46.166667,E,43.666667,S,41.833333,100.0

In [88]:
df_factor['변별도'] = (df_factor['1순위_점수'] - ((df_factor['2순위_점수']+df_factor['4순위_점수']))/2)
df_factor

,지역,학교명,학년,반,번호,성별,성명,interest_S,interest_E,interest_C,interest_R,interest_I,interest_A,person_S,person_E,person_C,person_R,person_I,person_A,apti_S,apti_E,apti_C,apti_R,apti_I,apti_A,env_D,env_I,env_P,env_T,job_S,job_E,job_C,job_R,job_I,job_A,interest_S_T,interest_E_T,interest_C_T,interest_R_T,interest_I_T,interest_A_T,person_S_T,person_E_T,person_C_T,person_R_T,person_I_T,person_A_T,apti_S_T,apti_E_T,apti_C_T,apti_R_T,apti_I_T,apti_A_T,job_S_T,job_E_T,job_C_T,job_R_T,job_I_T,job_A_T,env_D_T,env_I_T,env_P_T,env_T_T,factor_S,factor_E,factor_C,factor_R,factor_I,factor_A,1순위,1순위_점수,2순위,2순위_점수,3순위,3순위_점수,4순위,4순위_점수,5순위,5순위_점수,6순위,6순위_점수,반응적합,변별도
0,[한국],[행과고],2,2,27,1,[홍길동],3,2,3,5,4,7,5,8,5,5,4,7,11,10,11,7,8,12,6,4,4,7,9,11,12,10,6,10,35,30,35,45,40,53,50,65,50,50,45,60,54,51,54,43,46,57,48,52,55,50,41,50,49,43,42,50,46.000000,46.500000,47.166667,46.000000,43.000000,55.000000,A,55.000000,C,47.166667,E,46.500000,S,46.000000,R,46.000000,I,43.000000,100.0,8.416667
1,[한국],[행과고],3,5,17,2,[홍길동],3,8,4,4,2,3,4,3,5,5,6,5,13,10,12,11,7,11,3,9,3,7,9,8,13,12,10,14,34,54,38,38,30,34,44,39,49,49,55,49,59,50,56,53,43,53,49,47,59,56,51,62,40,59,39,51,46.500000,49.000000,49.333333,47.833333,42.000000,47.500000,C,49.333333,E,49.000000,R,47.833333,A,47.500000,S,46.500000,I,42.000000,100.0,1.083333
2,[한국],[행과고],3,3,20,1,[홍길동],4,5,6,1,5,3,8,4,7,7,5,6,12,13,7,13,10,10,4,4,6,4,9,12,9,10,13,9,40,45,49,25,45,35,65,45,60,60,50,55,57,60,43,60,51,51,48,55,48,50,58,48,43,43,47,42,51.166667,51.666667,48.666667,46.666667,50.000000,45.833333,E,51.666667,S,51.166667,I,50.000000,C,48.666667,R,46.666667,A,45.833333,100.0,1.750000
3,[한국],[행과고],2,3,9,2,[홍길동],2,6,6,3,5,2,5,6,5,5,3,5,6,8,15,11,6,10,4,8,4,4,10,9,10,11,16,11,30,46,46,34,42,30,49,55,49,49,39,49,40,45,65,53,40,50,51,49,51,53,67,53,44,56,42,42,40.000000,47.666667,53.666667,46.000000,45.000000,43.666667,C,53.666667,E,47.666667,R,46.000000,I,45.000000,A,43.666667,S,40.000000,100.0,7.333333
4,[한국],[행과고],1,1,7,1,[홍길동],6,3,7,3,3,2,3,2,4,8,8,7,12,12,7,14,16,11,6,6,4,6,18,9,9,7,14,9,49,35,53,35,35,30,39,34,45,65,65,60,57,57,43,63,69,54,73,48,48,43,61,48,49,49,42,47,54.000000,44.333333,47.500000,50.666667,55.666667,46.000000,I,55.666667,S,54.000000,R,50.666667,C,47.500000,A,46.000000,E,44.333333,100.0,4.916667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,[한국],[행과고],1,1,29,1,[홍길동],5,3,3,5,3,5,4,4,6,6,6,6,9,12,15,13,14,8,5,6,4,6,4,13,12,9,11,11,45,35,35,45,35,45,45,45,55,55,55,55,48,57,66,60,63,46,36,58,55,48,52,52,46,49,42,47,44.500000,47.833333,52.000000,52.166667,50.500000,48.166667,R,52.166667,C,52.000000,I,50.500000,A,48.166667,E,47.833333,S,44.500000,100.0,2.083333
9996,[한국],[행과고],2,4,8,1,[홍길동],5,4,4,3,5,3,6,6,4,5,4,5,7,12,13,10,11,11,2,9,4,7,12,2,12,12,8,8,45,40,40,35,45,35,55,55,45,50,45,50,43,57,60,51,54,54,55,30,55,55,46,46,35,58,42,50,47.666667,46.500000,50.000000,46.166667,48.166667,45.666667,C,50.000000,I,48.166667,S,47.666667,E,46.500000,R,46.166667,A,45.666667,100.0,2.666667
9997,[한국],[행과고],1,4,17,2,[홍길동],6,4,3,2,5,4,5,8,4,2,5,3,9,8,9,12,8,12,3,3,4,7,13,8,9,7,5,10,46,38,34,30,42,38,49,65,44,34,49,39,48,45,48,56,45,56,59,47,49,44,39,51,40,40,42,51,49.333333,46.333333,42.833333,41.666667,43.666667,46.333333,S,49.333333,E,46.333333,A,46.333333,I,43.666667,C,42.833333,R,41.666667,100.0,4.333333
9998,[한국],[행과고],3,3,13,2,[홍길동],2,6,2,5,5,4,6,6,4,5,4,6,5,6,8,13,8,13,2,8,3,8,12,7,7,5,5,7,30,46,30,42,42,38,55,55,44,49,44,55,37,40,45,59,45,59,56,44,44,39,39,44,35,56,39,54,40.833333,45.166667,39.666667,48.333333,42.833333,48.833333,A,48.833333,R,48.333333,E,45.166667,I,42.833333,S,40.833333,C,39.666667,100.0,3.250000
9999,[한국],[행과고],1,3,15,1,[홍길동],2,3,4,5,2,8,2,7,6,7,9,6,9,6,8,9,11,10,3,6,5,3,14,10,10,7,11,11,30,35,40,45,30,57,34,60,55,60,70,55,48,41,46,48,54,51,61,50,50,43,52,52,39,49,45,39,41.833333,43.666667,46.166667,48.166667,48.333333,53.833333,A,53.833333,I,48.333333,R,48.166667,C,46.166667,E,43.666667,S,41.833333,100.0,6.583333

In [89]:
#최적 코드 변별

df_factor['Code1'] = np.where(
    (df_factor['반응적합'] <= 70) | (df_factor['변별도'] < 1),  # 조건 1, 2 결합
    '분류불능',  # 조건 1 또는 2를 만족하면 '분류불능'
    np.where(
        df_factor['성별'].isna(),  # 조건 3
        None,  # 성별이 None이면 None
        df_factor['1순위'] + df_factor['2순위']  # 그 외에는 '1순위'와 '2순위' 결합
    )
)
df_factor

,지역,학교명,학년,반,번호,성별,성명,interest_S,interest_E,interest_C,interest_R,interest_I,interest_A,person_S,person_E,person_C,person_R,person_I,person_A,apti_S,apti_E,apti_C,apti_R,apti_I,apti_A,env_D,env_I,env_P,env_T,job_S,job_E,job_C,job_R,job_I,job_A,interest_S_T,interest_E_T,interest_C_T,interest_R_T,interest_I_T,interest_A_T,person_S_T,person_E_T,person_C_T,person_R_T,person_I_T,person_A_T,apti_S_T,apti_E_T,apti_C_T,apti_R_T,apti_I_T,apti_A_T,job_S_T,job_E_T,job_C_T,job_R_T,job_I_T,job_A_T,env_D_T,env_I_T,env_P_T,env_T_T,factor_S,factor_E,factor_C,factor_R,factor_I,factor_A,1순위,1순위_점수,2순위,2순위_점수,3순위,3순위_점수,4순위,4순위_점수,5순위,5순위_점수,6순위,6순위_점수,반응적합,변별도,Code1
0,[한국],[행과고],2,2,27,1,[홍길동],3,2,3,5,4,7,5,8,5,5,4,7,11,10,11,7,8,12,6,4,4,7,9,11,12,10,6,10,35,30,35,45,40,53,50,65,50,50,45,60,54,51,54,43,46,57,48,52,55,50,41,50,49,43,42,50,46.000000,46.500000,47.166667,46.000000,43.000000,55.000000,A,55.000000,C,47.166667,E,46.500000,S,46.000000,R,46.000000,I,43.000000,100.0,8.416667,AC
1,[한국],[행과고],3,5,17,2,[홍길동],3,8,4,4,2,3,4,3,5,5,6,5,13,10,12,11,7,11,3,9,3,7,9,8,13,12,10,14,34,54,38,38,30,34,44,39,49,49,55,49,59,50,56,53,43,53,49,47,59,56,51,62,40,59,39,51,46.500000,49.000000,49.333333,47.833333,42.000000,47.500000,C,49.333333,E,49.000000,R,47.833333,A,47.500000,S,46.500000,I,42.000000,100.0,1.083333,CE
2,[한국],[행과고],3,3,20,1,[홍길동],4,5,6,1,5,3,8,4,7,7,5,6,12,13,7,13,10,10,4,4,6,4,9,12,9,10,13,9,40,45,49,25,45,35,65,45,60,60,50,55,57,60,43,60,51,51,48,55,48,50,58,48,43,43,47,42,51.166667,51.666667,48.666667,46.666667,50.000000,45.833333,E,51.666667,S,51.166667,I,50.000000,C,48.666667,R,46.666667,A,45.833333,100.0,1.750000,ES
3,[한국],[행과고],2,3,9,2,[홍길동],2,6,6,3,5,2,5,6,5,5,3,5,6,8,15,11,6,10,4,8,4,4,10,9,10,11,16,11,30,46,46,34,42,30,49,55,49,49,39,49,40,45,65,53,40,50,51,49,51,53,67,53,44,56,42,42,40.000000,47.666667,53.666667,46.000000,45.000000,43.666667,C,53.666667,E,47.666667,R,46.000000,I,45.000000,A,43.666667,S,40.000000,100.0,7.333333,CE
4,[한국],[행과고],1,1,7,1,[홍길동],6,3,7,3,3,2,3,2,4,8,8,7,12,12,7,14,16,11,6,6,4,6,18,9,9,7,14,9,49,35,53,35,35,30,39,34,45,65,65,60,57,57,43,63,69,54,73,48,48,43,61,48,49,49,42,47,54.000000,44.333333,47.500000,50.666667,55.666667,46.000000,I,55.666667,S,54.000000,R,50.666667,C,47.500000,A,46.000000,E,44.333333,100.0,4.916667,IS
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,[한국],[행과고],1,1,29,1,[홍길동],5,3,3,5,3,5,4,4,6,6,6,6,9,12,15,13,14,8,5,6,4,6,4,13,12,9,11,11,45,35,35,45,35,45,45,45,55,55,55,55,48,57,66,60,63,46,36,58,55,48,52,52,46,49,42,47,44.500000,47.833333,52.000000,52.166667,50.500000,48.166667,R,52.166667,C,52.000000,I,50.500000,A,48.166667,E,47.833333,S,44.500000,100.0,2.083333,RC
9996,[한국],[행과고],2,4,8,1,[홍길동],5,4,4,3,5,3,6,6,4,5,4,5,7,12,13,10,11,11,2,9,4,7,12,2,12,12,8,8,45,40,40,35,45,35,55,55,45,50,45,50,43,57,60,51,54,54,55,30,55,55,46,46,35,58,42,50,47.666667,46.500000,50.000000,46.166667,48.166667,45.666667,C,50.000000,I,48.166667,S,47.666667,E,46.500000,R,46.166667,A,45.666667,100.0,2.666667,CI
9997,[한국],[행과고],1,4,17,2,[홍길동],6,4,3,2,5,4,5,8,4,2,5,3,9,8,9,12,8,12,3,3,4,7,13,8,9,7,5,10,46,38,34,30,42,38,49,65,44,34,49,39,48,45,48,56,45,56,59,47,49,44,39,51,40,40,42,51,49.333333,46.333333,42.833333,41.666667,43.666667,46.333333,S,49.333333,E,46.333333,A,46.333333,I,43.666667,C,42.833333,R,41.666667,100.0,4.333333,SE
9998,[한국],[행과고],3,3,13,2,[홍길동],2,6,2,5,5,4,6,6,4,5,4,6,5,6,8,13,8,13,2,8,3,8,12,7,7,5,5,7,30,46,30,42,42,38,55,55,44,49,44,55,37,40,45,59,45,59,56,44,44,39,39,44,35,56,39,54,40.833333,45.166667,39.666667,48.333333,42.833333,48.833333,A,48.833333,R,48.333333,E,45.166667,I,42.833333,S,40.833333,C,39.666667,100.0,3.250000,AR
9999,[한국],[행과고],1,3,15,1,[홍길동],2,3,4,5,2,8,2,7,6,7,9,6,9,6,8,9,11,10,3,6,5,3,14,10,10,7,11,11,30,35,40,45,30,57,34,60,55,60,70,55,48,41,46,48,54,51,61,50,50,43,52,52,39,49,45,39,41.833333,43.666667,46.166667,48.166667,48.333333,53.833333,A,53.833333,I,48.333333,R,48.166667,C,46.166667,E,43.666667,S,41.833333,100.0,6.583333,AI

In [90]:
#적합 코드 변별

df_factor['Code2'] = np.where(
    (df_factor['Code1'] == '분류불능'), '분류불능',
    np.where(df_factor['2순위_점수']-df_factor['3순위_점수']>=3, (df_factor['2순위']+df_factor['1순위']),
             (df_factor['1순위']+df_factor['3순위']))
)

df_factor

,지역,학교명,학년,반,번호,성별,성명,interest_S,interest_E,interest_C,interest_R,interest_I,interest_A,person_S,person_E,person_C,person_R,person_I,person_A,apti_S,apti_E,apti_C,apti_R,apti_I,apti_A,env_D,env_I,env_P,env_T,job_S,job_E,job_C,job_R,job_I,job_A,interest_S_T,interest_E_T,interest_C_T,interest_R_T,interest_I_T,interest_A_T,person_S_T,person_E_T,person_C_T,person_R_T,person_I_T,person_A_T,apti_S_T,apti_E_T,apti_C_T,apti_R_T,apti_I_T,apti_A_T,job_S_T,job_E_T,job_C_T,job_R_T,job_I_T,job_A_T,env_D_T,env_I_T,env_P_T,env_T_T,factor_S,factor_E,factor_C,factor_R,factor_I,factor_A,1순위,1순위_점수,2순위,2순위_점수,3순위,3순위_점수,4순위,4순위_점수,5순위,5순위_점수,6순위,6순위_점수,반응적합,변별도,Code1,Code2
0,[한국],[행과고],2,2,27,1,[홍길동],3,2,3,5,4,7,5,8,5,5,4,7,11,10,11,7,8,12,6,4,4,7,9,11,12,10,6,10,35,30,35,45,40,53,50,65,50,50,45,60,54,51,54,43,46,57,48,52,55,50,41,50,49,43,42,50,46.000000,46.500000,47.166667,46.000000,43.000000,55.000000,A,55.000000,C,47.166667,E,46.500000,S,46.000000,R,46.000000,I,43.000000,100.0,8.416667,AC,AE
1,[한국],[행과고],3,5,17,2,[홍길동],3,8,4,4,2,3,4,3,5,5,6,5,13,10,12,11,7,11,3,9,3,7,9,8,13,12,10,14,34,54,38,38,30,34,44,39,49,49,55,49,59,50,56,53,43,53,49,47,59,56,51,62,40,59,39,51,46.500000,49.000000,49.333333,47.833333,42.000000,47.500000,C,49.333333,E,49.000000,R,47.833333,A,47.500000,S,46.500000,I,42.000000,100.0,1.083333,CE,CR
2,[한국],[행과고],3,3,20,1,[홍길동],4,5,6,1,5,3,8,4,7,7,5,6,12,13,7,13,10,10,4,4,6,4,9,12,9,10,13,9,40,45,49,25,45,35,65,45,60,60,50,55,57,60,43,60,51,51,48,55,48,50,58,48,43,43,47,42,51.166667,51.666667,48.666667,46.666667,50.000000,45.833333,E,51.666667,S,51.166667,I,50.000000,C,48.666667,R,46.666667,A,45.833333,100.0,1.750000,ES,EI
3,[한국],[행과고],2,3,9,2,[홍길동],2,6,6,3,5,2,5,6,5,5,3,5,6,8,15,11,6,10,4,8,4,4,10,9,10,11,16,11,30,46,46,34,42,30,49,55,49,49,39,49,40,45,65,53,40,50,51,49,51,53,67,53,44,56,42,42,40.000000,47.666667,53.666667,46.000000,45.000000,43.666667,C,53.666667,E,47.666667,R,46.000000,I,45.000000,A,43.666667,S,40.000000,100.0,7.333333,CE,CR
4,[한국],[행과고],1,1,7,1,[홍길동],6,3,7,3,3,2,3,2,4,8,8,7,12,12,7,14,16,11,6,6,4,6,18,9,9,7,14,9,49,35,53,35,35,30,39,34,45,65,65,60,57,57,43,63,69,54,73,48,48,43,61,48,49,49,42,47,54.000000,44.333333,47.500000,50.666667,55.666667,46.000000,I,55.666667,S,54.000000,R,50.666667,C,47.500000,A,46.000000,E,44.333333,100.0,4.916667,IS,SI
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,[한국],[행과고],1,1,29,1,[홍길동],5,3,3,5,3,5,4,4,6,6,6,6,9,12,15,13,14,8,5,6,4,6,4,13,12,9,11,11,45,35,35,45,35,45,45,45,55,55,55,55,48,57,66,60,63,46,36,58,55,48,52,52,46,49,42,47,44.500000,47.833333,52.000000,52.166667,50.500000,48.166667,R,52.166667,C,52.000000,I,50.500000,A,48.166667,E,47.833333,S,44.500000,100.0,2.083333,RC,RI
9996,[한국],[행과고],2,4,8,1,[홍길동],5,4,4,3,5,3,6,6,4,5,4,5,7,12,13,10,11,11,2,9,4,7,12,2,12,12,8,8,45,40,40,35,45,35,55,55,45,50,45,50,43,57,60,51,54,54,55,30,55,55,46,46,35,58,42,50,47.666667,46.500000,50.000000,46.166667,48.166667,45.666667,C,50.000000,I,48.166667,S,47.666667,E,46.500000,R,46.166667,A,45.666667,100.0,2.666667,CI,CS
9997,[한국],[행과고],1,4,17,2,[홍길동],6,4,3,2,5,4,5,8,4,2,5,3,9,8,9,12,8,12,3,3,4,7,13,8,9,7,5,10,46,38,34,30,42,38,49,65,44,34,49,39,48,45,48,56,45,56,59,47,49,44,39,51,40,40,42,51,49.333333,46.333333,42.833333,41.666667,43.666667,46.333333,S,49.333333,E,46.333333,A,46.333333,I,43.666667,C,42.833333,R,41.666667,100.0,4.333333,SE,SA
9998,[한국],[행과고],3,3,13,2,[홍길동],2,6,2,5,5,4,6,6,4,5,4,6,5,6,8,13,8,13,2,8,3,8,12,7,7,5,5,7,30,46,30,42,42,38,55,55,44,49,44,55,37,40,45,59,45,59,56,44,44,39,39,44,35,56,39,54,40.833333,45.166667,39.666667,48.333333,42.833333,48.833333,A,48.833333,R,48.333333,E,45.166667,I,42.833333,S,40.833333,C,39.666667,100.0,3.250000,AR,RA
9999,[한국],[행과고],1,3,15,1,[홍길동],2,3,4,5,2,8,2,7,6,7,9,6,9,6,8,9,11,10,3,6,5,3,14,10,10,7,11,11,30,35,40,45,30,57,34,60,55,60,70,55,48,41,46,48,54,51,61,50,50,43,52,52,39,49,45,39,41.833333,43.666667,46.166667,48.166667,48.333333,53.833333,A,53.833333,I,48.333333,R,48.166667,C,46.166667,E,43.666667,S,41.833333,100.0,6.583333,AI,AR

In [91]:
#1순위 2순위 코드 넘버링
#S:1, E:2, C:3, R:4, I:5, A:6
priority_mapping = {'S': 1, 'E': 2, 'C': 3, 'R': 4, 'I': 5, 'A': 6}
df_factor['1순위 코드 넘버'] = df_factor['1순위'].map(priority_mapping)
df_factor['2순위 코드 넘버'] = df_factor['2순위'].map(priority_mapping)

df_factor

,지역,학교명,학년,반,번호,성별,성명,interest_S,interest_E,interest_C,interest_R,interest_I,interest_A,person_S,person_E,person_C,person_R,person_I,person_A,apti_S,apti_E,apti_C,apti_R,apti_I,apti_A,env_D,env_I,env_P,env_T,job_S,job_E,job_C,job_R,job_I,job_A,interest_S_T,interest_E_T,interest_C_T,interest_R_T,interest_I_T,interest_A_T,person_S_T,person_E_T,person_C_T,person_R_T,person_I_T,person_A_T,apti_S_T,apti_E_T,apti_C_T,apti_R_T,apti_I_T,apti_A_T,job_S_T,job_E_T,job_C_T,job_R_T,job_I_T,job_A_T,env_D_T,env_I_T,env_P_T,env_T_T,factor_S,factor_E,factor_C,factor_R,factor_I,factor_A,1순위,1순위_점수,2순위,2순위_점수,3순위,3순위_점수,4순위,4순위_점수,5순위,5순위_점수,6순위,6순위_점수,반응적합,변별도,Code1,Code2,1순위 코드 넘버,2순위 코드 넘버
0,[한국],[행과고],2,2,27,1,[홍길동],3,2,3,5,4,7,5,8,5,5,4,7,11,10,11,7,8,12,6,4,4,7,9,11,12,10,6,10,35,30,35,45,40,53,50,65,50,50,45,60,54,51,54,43,46,57,48,52,55,50,41,50,49,43,42,50,46.000000,46.500000,47.166667,46.000000,43.000000,55.000000,A,55.000000,C,47.166667,E,46.500000,S,46.000000,R,46.000000,I,43.000000,100.0,8.416667,AC,AE,6,3
1,[한국],[행과고],3,5,17,2,[홍길동],3,8,4,4,2,3,4,3,5,5,6,5,13,10,12,11,7,11,3,9,3,7,9,8,13,12,10,14,34,54,38,38,30,34,44,39,49,49,55,49,59,50,56,53,43,53,49,47,59,56,51,62,40,59,39,51,46.500000,49.000000,49.333333,47.833333,42.000000,47.500000,C,49.333333,E,49.000000,R,47.833333,A,47.500000,S,46.500000,I,42.000000,100.0,1.083333,CE,CR,3,2
2,[한국],[행과고],3,3,20,1,[홍길동],4,5,6,1,5,3,8,4,7,7,5,6,12,13,7,13,10,10,4,4,6,4,9,12,9,10,13,9,40,45,49,25,45,35,65,45,60,60,50,55,57,60,43,60,51,51,48,55,48,50,58,48,43,43,47,42,51.166667,51.666667,48.666667,46.666667,50.000000,45.833333,E,51.666667,S,51.166667,I,50.000000,C,48.666667,R,46.666667,A,45.833333,100.0,1.750000,ES,EI,2,1
3,[한국],[행과고],2,3,9,2,[홍길동],2,6,6,3,5,2,5,6,5,5,3,5,6,8,15,11,6,10,4,8,4,4,10,9,10,11,16,11,30,46,46,34,42,30,49,55,49,49,39,49,40,45,65,53,40,50,51,49,51,53,67,53,44,56,42,42,40.000000,47.666667,53.666667,46.000000,45.000000,43.666667,C,53.666667,E,47.666667,R,46.000000,I,45.000000,A,43.666667,S,40.000000,100.0,7.333333,CE,CR,3,2
4,[한국],[행과고],1,1,7,1,[홍길동],6,3,7,3,3,2,3,2,4,8,8,7,12,12,7,14,16,11,6,6,4,6,18,9,9,7,14,9,49,35,53,35,35,30,39,34,45,65,65,60,57,57,43,63,69,54,73,48,48,43,61,48,49,49,42,47,54.000000,44.333333,47.500000,50.666667,55.666667,46.000000,I,55.666667,S,54.000000,R,50.666667,C,47.500000,A,46.000000,E,44.333333,100.0,4.916667,IS,SI,5,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,[한국],[행과고],1,1,29,1,[홍길동],5,3,3,5,3,5,4,4,6,6,6,6,9,12,15,13,14,8,5,6,4,6,4,13,12,9,11,11,45,35,35,45,35,45,45,45,55,55,55,55,48,57,66,60,63,46,36,58,55,48,52,52,46,49,42,47,44.500000,47.833333,52.000000,52.166667,50.500000,48.166667,R,52.166667,C,52.000000,I,50.500000,A,48.166667,E,47.833333,S,44.500000,100.0,2.083333,RC,RI,4,3
9996,[한국],[행과고],2,4,8,1,[홍길동],5,4,4,3,5,3,6,6,4,5,4,5,7,12,13,10,11,11,2,9,4,7,12,2,12,12,8,8,45,40,40,35,45,35,55,55,45,50,45,50,43,57,60,51,54,54,55,30,55,55,46,46,35,58,42,50,47.666667,46.500000,50.000000,46.166667,48.166667,45.666667,C,50.000000,I,48.166667,S,47.666667,E,46.500000,R,46.166667,A,45.666667,100.0,2.666667,CI,CS,3,5
9997,[한국],[행과고],1,4,17,2,[홍길동],6,4,3,2,5,4,5,8,4,2,5,3,9,8,9,12,8,12,3,3,4,7,13,8,9,7,5,10,46,38,34,30,42,38,49,65,44,34,49,39,48,45,48,56,45,56,59,47,49,44,39,51,40,40,42,51,49.333333,46.333333,42.833333,41.666667,43.666667,46.333333,S,49.333333,E,46.333333,A,46.333333,I,43.666667,C,42.833333,R,41.666667,100.0,4.333333,SE,SA,1,2
9998,[한국],[행과고],3,3,13,2,[홍길동],2,6,2,5,5,4,6,6,4,5,4,6,5,6,8,13,8,13,2,8,3,8,12,7,7,5,5,7,30,46,30,42,42,38,55,55,44,49,44,55,37,40,45,59,45,59,56,44,44,39,39,44,35,56,39,54,40.833333,45.166667,39.666667,48.333333,42.833333,48.833333,A,48.833333,R,48.333333,E,45.166667,I,42.833333,S,40.833333,C,39.666667,100.0,3.250000,AR,RA,6,4
9999,[한국],[행과고],1,3,15,1,[홍길동],2,3,4,5,2,8,2,7,6,7,9,6,9,6,8,9,11,10,3,6,5,3,14,10,10,7,11,11,30,35,40,45,30,57,34,60,55,60,70,55,48,41,46,48,54,51,61,50,50,43,52,52,39,49,45,39,41.833333,43.666667,46.166667,48.166667,48.333333,53.833333,A,53.833333,I,48.333333,R,48.166667,C,46.166667,E,43.666667,S,41.833333,100.0,6.583333,AI,AR,6,5

In [92]:
##직업 환경 코드 변별

conditions = [
    df_factor['env_P_T'] > df_factor['env_T_T'],  # env_P_T가 더 큰 경우
    df_factor['env_P_T'] < df_factor['env_T_T'],  # env_T_T가 더 큰 경우
    (df_factor['env_P_T'] == df_factor['env_T_T']) & df_factor['1순위 코드 넘버'].isin([1, 2, 3])  # env_P_T == env_T_T이면서 1순위 코드 넘버가 1, 2, 3인 경우
]

# 각 조건에 해당하는 결과 값
choices = ['P', 'T', 'P']

# 기본 값 정의 (위 조건에 해당하지 않는 경우)
default_value = 'T'

# numpy.select로 '직환code1' 컬럼 생성
df_factor['직환code1'] = np.select(conditions, choices, default=default_value)

conditions2 = [
    df_factor['env_D_T'] > df_factor['env_I_T'],  # env_P_T가 더 큰 경우
    df_factor['env_D_T'] < df_factor['env_I_T'],  # env_T_T가 더 큰 경우
    (df_factor['env_D_T'] == df_factor['env_I_T']) & df_factor['1순위 코드 넘버'].isin([1, 2, 3])  # env_P_T == env_T_T이면서 1순위 코드 넘버가 1, 2, 3인 경우
]

# 각 조건에 해당하는 결과 값
choices2 = ['D', 'I', 'D']

# 기본 값 정의 (위 조건에 해당하지 않는 경우)
default_value2 = 'I'

# numpy.select로 '직환code1' 컬럼 생성
df_factor['직환code2'] = np.select(conditions2, choices2, default=default_value2)



df_factor

,지역,학교명,학년,반,번호,성별,성명,interest_S,interest_E,interest_C,interest_R,interest_I,interest_A,person_S,person_E,person_C,person_R,person_I,person_A,apti_S,apti_E,apti_C,apti_R,apti_I,apti_A,env_D,env_I,env_P,env_T,job_S,job_E,job_C,job_R,job_I,job_A,interest_S_T,interest_E_T,interest_C_T,interest_R_T,interest_I_T,interest_A_T,person_S_T,person_E_T,person_C_T,person_R_T,person_I_T,person_A_T,apti_S_T,apti_E_T,apti_C_T,apti_R_T,apti_I_T,apti_A_T,job_S_T,job_E_T,job_C_T,job_R_T,job_I_T,job_A_T,env_D_T,env_I_T,env_P_T,env_T_T,factor_S,factor_E,factor_C,factor_R,factor_I,factor_A,1순위,1순위_점수,2순위,2순위_점수,3순위,3순위_점수,4순위,4순위_점수,5순위,5순위_점수,6순위,6순위_점수,반응적합,변별도,Code1,Code2,1순위 코드 넘버,2순위 코드 넘버,직환code1,직환code2
0,[한국],[행과고],2,2,27,1,[홍길동],3,2,3,5,4,7,5,8,5,5,4,7,11,10,11,7,8,12,6,4,4,7,9,11,12,10,6,10,35,30,35,45,40,53,50,65,50,50,45,60,54,51,54,43,46,57,48,52,55,50,41,50,49,43,42,50,46.000000,46.500000,47.166667,46.000000,43.000000,55.000000,A,55.000000,C,47.166667,E,46.500000,S,46.000000,R,46.000000,I,43.000000,100.0,8.416667,AC,AE,6,3,T,D
1,[한국],[행과고],3,5,17,2,[홍길동],3,8,4,4,2,3,4,3,5,5,6,5,13,10,12,11,7,11,3,9,3,7,9,8,13,12,10,14,34,54,38,38,30,34,44,39,49,49,55,49,59,50,56,53,43,53,49,47,59,56,51,62,40,59,39,51,46.500000,49.000000,49.333333,47.833333,42.000000,47.500000,C,49.333333,E,49.000000,R,47.833333,A,47.500000,S,46.500000,I,42.000000,100.0,1.083333,CE,CR,3,2,T,I
2,[한국],[행과고],3,3,20,1,[홍길동],4,5,6,1,5,3,8,4,7,7,5,6,12,13,7,13,10,10,4,4,6,4,9,12,9,10,13,9,40,45,49,25,45,35,65,45,60,60,50,55,57,60,43,60,51,51,48,55,48,50,58,48,43,43,47,42,51.166667,51.666667,48.666667,46.666667,50.000000,45.833333,E,51.666667,S,51.166667,I,50.000000,C,48.666667,R,46.666667,A,45.833333,100.0,1.750000,ES,EI,2,1,P,D
3,[한국],[행과고],2,3,9,2,[홍길동],2,6,6,3,5,2,5,6,5,5,3,5,6,8,15,11,6,10,4,8,4,4,10,9,10,11,16,11,30,46,46,34,42,30,49,55,49,49,39,49,40,45,65,53,40,50,51,49,51,53,67,53,44,56,42,42,40.000000,47.666667,53.666667,46.000000,45.000000,43.666667,C,53.666667,E,47.666667,R,46.000000,I,45.000000,A,43.666667,S,40.000000,100.0,7.333333,CE,CR,3,2,P,I
4,[한국],[행과고],1,1,7,1,[홍길동],6,3,7,3,3,2,3,2,4,8,8,7,12,12,7,14,16,11,6,6,4,6,18,9,9,7,14,9,49,35,53,35,35,30,39,34,45,65,65,60,57,57,43,63,69,54,73,48,48,43,61,48,49,49,42,47,54.000000,44.333333,47.500000,50.666667,55.666667,46.000000,I,55.666667,S,54.000000,R,50.666667,C,47.500000,A,46.000000,E,44.333333,100.0,4.916667,IS,SI,5,1,T,I
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,[한국],[행과고],1,1,29,1,[홍길동],5,3,3,5,3,5,4,4,6,6,6,6,9,12,15,13,14,8,5,6,4,6,4,13,12,9,11,11,45,35,35,45,35,45,45,45,55,55,55,55,48,57,66,60,63,46,36,58,55,48,52,52,46,49,42,47,44.500000,47.833333,52.000000,52.166667,50.500000,48.166667,R,52.166667,C,52.000000,I,50.500000,A,48.166667,E,47.833333,S,44.500000,100.0,2.083333,RC,RI,4,3,T,I
9996,[한국],[행과고],2,4,8,1,[홍길동],5,4,4,3,5,3,6,6,4,5,4,5,7,12,13,10,11,11,2,9,4,7,12,2,12,12,8,8,45,40,40,35,45,35,55,55,45,50,45,50,43,57,60,51,54,54,55,30,55,55,46,46,35,58,42,50,47.666667,46.500000,50.000000,46.166667,48.166667,45.666667,C,50.000000,I,48.166667,S,47.666667,E,46.500000,R,46.166667,A,45.666667,100.0,2.666667,CI,CS,3,5,T,I
9997,[한국],[행과고],1,4,17,2,[홍길동],6,4,3,2,5,4,5,8,4,2,5,3,9,8,9,12,8,12,3,3,4,7,13,8,9,7,5,10,46,38,34,30,42,38,49,65,44,34,49,39,48,45,48,56,45,56,59,47,49,44,39,51,40,40,42,51,49.333333,46.333333,42.833333,41.666667,43.666667,46.333333,S,49.333333,E,46.333333,A,46.333333,I,43.666667,C,42.833333,R,41.666667,100.0,4.333333,SE,SA,1,2,T,D
9998,[한국],[행과고],3,3,13,2,[홍길동],2,6,2,5,5,4,6,6,4,5,4,6,5,6,8,13,8,13,2,8,3,8,12,7,7,5,5,7,30,46,30,42,42,38,55,55,44,49,44,55,37,40,45,59,45,59,56,44,44,39,39,44,35,56,39,54,40.833333,45.166667,39.666667,48.333333,42.833333,48.833333,A,48.833333,R,48.333333,E,45.166667,I,42.833333,S,40.833333,C,39.666667,100.0,3.250000,AR,RA,6,4,T,I
9999,[한국],[행과고],1,3,15,1,[홍길동],2,3,4,5,2,8,2,7,6,7,9,6,9,6,8,9,11,10,3,6,5,3,14,10,10,7,11,11,30,35,40,45,30,57,34,60,55,60,70,55,48,41,46,48,54,51,61,50,50,43,52,52,39,49,45,39,41.833333,43.666667,46.166667,48.166667,48.333333,53.833333,A,53.833333,I,48.333333,R,48.166667,C,46.166667,E,43.666667,S,41.833333,100.0,6.583333,AI,AR,6,5,P,I

In [93]:
df_factor['직업환경 Code'] = np.where((df_factor['env_D_T'] < 30)&(df_factor['env_I_T']<30)&(df_factor['env_P_T']<30)&(df_factor['env_T_T']<30) , '분류불능',
                                  (df_factor['직환code2']+df_factor['직환code1']))

df_factor

,지역,학교명,학년,반,번호,성별,성명,interest_S,interest_E,interest_C,interest_R,interest_I,interest_A,person_S,person_E,person_C,person_R,person_I,person_A,apti_S,apti_E,apti_C,apti_R,apti_I,apti_A,env_D,env_I,env_P,env_T,job_S,job_E,job_C,job_R,job_I,job_A,interest_S_T,interest_E_T,interest_C_T,interest_R_T,interest_I_T,interest_A_T,person_S_T,person_E_T,person_C_T,person_R_T,person_I_T,person_A_T,apti_S_T,apti_E_T,apti_C_T,apti_R_T,apti_I_T,apti_A_T,job_S_T,job_E_T,job_C_T,job_R_T,job_I_T,job_A_T,env_D_T,env_I_T,env_P_T,env_T_T,factor_S,factor_E,factor_C,factor_R,factor_I,factor_A,1순위,1순위_점수,2순위,2순위_점수,3순위,3순위_점수,4순위,4순위_점수,5순위,5순위_점수,6순위,6순위_점수,반응적합,변별도,Code1,Code2,1순위 코드 넘버,2순위 코드 넘버,직환code1,직환code2,직업환경 Code
0,[한국],[행과고],2,2,27,1,[홍길동],3,2,3,5,4,7,5,8,5,5,4,7,11,10,11,7,8,12,6,4,4,7,9,11,12,10,6,10,35,30,35,45,40,53,50,65,50,50,45,60,54,51,54,43,46,57,48,52,55,50,41,50,49,43,42,50,46.000000,46.500000,47.166667,46.000000,43.000000,55.000000,A,55.000000,C,47.166667,E,46.500000,S,46.000000,R,46.000000,I,43.000000,100.0,8.416667,AC,AE,6,3,T,D,DT
1,[한국],[행과고],3,5,17,2,[홍길동],3,8,4,4,2,3,4,3,5,5,6,5,13,10,12,11,7,11,3,9,3,7,9,8,13,12,10,14,34,54,38,38,30,34,44,39,49,49,55,49,59,50,56,53,43,53,49,47,59,56,51,62,40,59,39,51,46.500000,49.000000,49.333333,47.833333,42.000000,47.500000,C,49.333333,E,49.000000,R,47.833333,A,47.500000,S,46.500000,I,42.000000,100.0,1.083333,CE,CR,3,2,T,I,IT
2,[한국],[행과고],3,3,20,1,[홍길동],4,5,6,1,5,3,8,4,7,7,5,6,12,13,7,13,10,10,4,4,6,4,9,12,9,10,13,9,40,45,49,25,45,35,65,45,60,60,50,55,57,60,43,60,51,51,48,55,48,50,58,48,43,43,47,42,51.166667,51.666667,48.666667,46.666667,50.000000,45.833333,E,51.666667,S,51.166667,I,50.000000,C,48.666667,R,46.666667,A,45.833333,100.0,1.750000,ES,EI,2,1,P,D,DP
3,[한국],[행과고],2,3,9,2,[홍길동],2,6,6,3,5,2,5,6,5,5,3,5,6,8,15,11,6,10,4,8,4,4,10,9,10,11,16,11,30,46,46,34,42,30,49,55,49,49,39,49,40,45,65,53,40,50,51,49,51,53,67,53,44,56,42,42,40.000000,47.666667,53.666667,46.000000,45.000000,43.666667,C,53.666667,E,47.666667,R,46.000000,I,45.000000,A,43.666667,S,40.000000,100.0,7.333333,CE,CR,3,2,P,I,IP
4,[한국],[행과고],1,1,7,1,[홍길동],6,3,7,3,3,2,3,2,4,8,8,7,12,12,7,14,16,11,6,6,4,6,18,9,9,7,14,9,49,35,53,35,35,30,39,34,45,65,65,60,57,57,43,63,69,54,73,48,48,43,61,48,49,49,42,47,54.000000,44.333333,47.500000,50.666667,55.666667,46.000000,I,55.666667,S,54.000000,R,50.666667,C,47.500000,A,46.000000,E,44.333333,100.0,4.916667,IS,SI,5,1,T,I,IT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,[한국],[행과고],1,1,29,1,[홍길동],5,3,3,5,3,5,4,4,6,6,6,6,9,12,15,13,14,8,5,6,4,6,4,13,12,9,11,11,45,35,35,45,35,45,45,45,55,55,55,55,48,57,66,60,63,46,36,58,55,48,52,52,46,49,42,47,44.500000,47.833333,52.000000,52.166667,50.500000,48.166667,R,52.166667,C,52.000000,I,50.500000,A,48.166667,E,47.833333,S,44.500000,100.0,2.083333,RC,RI,4,3,T,I,IT
9996,[한국],[행과고],2,4,8,1,[홍길동],5,4,4,3,5,3,6,6,4,5,4,5,7,12,13,10,11,11,2,9,4,7,12,2,12,12,8,8,45,40,40,35,45,35,55,55,45,50,45,50,43,57,60,51,54,54,55,30,55,55,46,46,35,58,42,50,47.666667,46.500000,50.000000,46.166667,48.166667,45.666667,C,50.000000,I,48.166667,S,47.666667,E,46.500000,R,46.166667,A,45.666667,100.0,2.666667,CI,CS,3,5,T,I,IT
9997,[한국],[행과고],1,4,17,2,[홍길동],6,4,3,2,5,4,5,8,4,2,5,3,9,8,9,12,8,12,3,3,4,7,13,8,9,7,5,10,46,38,34,30,42,38,49,65,44,34,49,39,48,45,48,56,45,56,59,47,49,44,39,51,40,40,42,51,49.333333,46.333333,42.833333,41.666667,43.666667,46.333333,S,49.333333,E,46.333333,A,46.333333,I,43.666667,C,42.833333,R,41.666667,100.0,4.333333,SE,SA,1,2,T,D,DT
9998,[한국],[행과고],3,3,13,2,[홍길동],2,6,2,5,5,4,6,6,4,5,4,6,5,6,8,13,8,13,2,8,3,8,12,7,7,5,5,7,30,46,30,42,42,38,55,55,44,49,44,55,37,40,45,59,45,59,56,44,44,39,39,44,35,56,39,54,40.833333,45.166667,39.666667,48.333333,42.833333,48.833333,A,48.833333,R,48.333333,E,45.166667,I,42.833333,S,40.833333,C,39.666667,100.0,3.250000,AR,RA,6,4,T,I,IT
9999,[한국],[행과고],1,3,15,1,[홍길동],2,3,4,5,2,8,2,7,6,7,9,6,9,6,8,9,11,10,3,6,5,3,14,10,10,7,11,11,30,35,40,45,30,57,34,60,55,60,70,55,48,41,46,48,54,51,61,50,50,43,52,52,39,49,45,39,41.833333,43.666667,46.166667,48.166667,48.333333,53.833333,A,53.833333,I,48.333333,R,48.166667,C,46.166667,E,43.666667,S,41.833333,100.0,6.583333,AI,AR,6,5,P,I,IP

In [94]:
major = pd.read_excel("C:\\Users\\user\\Desktop\\logic\\score.xlsx",sheet_name="major")
joblist = pd.read_excel("C:\\Users\\user\\Desktop\\logic\\score.xlsx",sheet_name="joblist")

In [95]:
df_factor['major'] = np.where((df_factor['Code1'] == '분류불능'), 
                              '분류불능', df_factor['Code1'].map(dict(zip(major['code'], major['major']))))
df_factor['joblist'] = np.where((df_factor['Code1'] == '분류불능'),
                                '분류불능', df_factor['Code1'].map(dict(zip(joblist['code'], joblist['job']))))
df_factor

,지역,학교명,학년,반,번호,성별,성명,interest_S,interest_E,interest_C,interest_R,interest_I,interest_A,person_S,person_E,person_C,person_R,person_I,person_A,apti_S,apti_E,apti_C,apti_R,apti_I,apti_A,env_D,env_I,env_P,env_T,job_S,job_E,job_C,job_R,job_I,job_A,interest_S_T,interest_E_T,interest_C_T,interest_R_T,interest_I_T,interest_A_T,person_S_T,person_E_T,person_C_T,person_R_T,person_I_T,person_A_T,apti_S_T,apti_E_T,apti_C_T,apti_R_T,apti_I_T,apti_A_T,job_S_T,job_E_T,job_C_T,job_R_T,job_I_T,job_A_T,env_D_T,env_I_T,env_P_T,env_T_T,factor_S,factor_E,factor_C,factor_R,factor_I,factor_A,1순위,1순위_점수,2순위,2순위_점수,3순위,3순위_점수,4순위,4순위_점수,5순위,5순위_점수,6순위,6순위_점수,반응적합,변별도,Code1,Code2,1순위 코드 넘버,2순위 코드 넘버,직환code1,직환code2,직업환경 Code,major,joblist
0,[한국],[행과고],2,2,27,1,[홍길동],3,2,3,5,4,7,5,8,5,5,4,7,11,10,11,7,8,12,6,4,4,7,9,11,12,10,6,10,35,30,35,45,40,53,50,65,50,50,45,60,54,51,54,43,46,57,48,52,55,50,41,50,49,43,42,50,46.000000,46.500000,47.166667,46.000000,43.000000,55.000000,A,55.000000,C,47.166667,E,46.500000,S,46.000000,R,46.000000,I,43.000000,100.0,8.416667,AC,AE,6,3,T,D,DT,"공예디자인과, 만화창작과, 삽화디자인과, 애니메이션학과, 의상디자인과 등","공예가, 광택미술가, 삽화가, 서예가, 소형세트구성가, 실내장식가, 애니메이터, 영..."
1,[한국],[행과고],3,5,17,2,[홍길동],3,8,4,4,2,3,4,3,5,5,6,5,13,10,12,11,7,11,3,9,3,7,9,8,13,12,10,14,34,54,38,38,30,34,44,39,49,49,55,49,59,50,56,53,43,53,49,47,59,56,51,62,40,59,39,51,46.500000,49.000000,49.333333,47.833333,42.000000,47.500000,C,49.333333,E,49.000000,R,47.833333,A,47.500000,S,46.500000,I,42.000000,100.0,1.083333,CE,CR,3,2,T,I,IT,"경찰행정학과, 산업안전과, 세무회계정보과, 지적학과, 행정학과 등","감정평가사, 경리사원, 공인회계사, 금전출납원, 기획사무 종사자, 비용회계사, 시설..."
2,[한국],[행과고],3,3,20,1,[홍길동],4,5,6,1,5,3,8,4,7,7,5,6,12,13,7,13,10,10,4,4,6,4,9,12,9,10,13,9,40,45,49,25,45,35,65,45,60,60,50,55,57,60,43,60,51,51,48,55,48,50,58,48,43,43,47,42,51.166667,51.666667,48.666667,46.666667,50.000000,45.833333,E,51.666667,S,51.166667,I,50.000000,C,48.666667,R,46.666667,A,45.833333,100.0,1.750000,ES,EI,2,1,P,D,DP,"경영학과, 국제경영학과, 마케팅학과, 언론정보학과, 정치외교학과, 호텔경영학과 등","공인중개사, 광고대행업자, 기업경영인, 로비스트, 무역업자, 변호사, 보험설계사, ..."
3,[한국],[행과고],2,3,9,2,[홍길동],2,6,6,3,5,2,5,6,5,5,3,5,6,8,15,11,6,10,4,8,4,4,10,9,10,11,16,11,30,46,46,34,42,30,49,55,49,49,39,49,40,45,65,53,40,50,51,49,51,53,67,53,44,56,42,42,40.000000,47.666667,53.666667,46.000000,45.000000,43.666667,C,53.666667,E,47.666667,R,46.000000,I,45.000000,A,43.666667,S,40.000000,100.0,7.333333,CE,CR,3,2,P,I,IP,"경찰행정학과, 산업안전과, 세무회계정보과, 지적학과, 행정학과 등","감정평가사, 경리사원, 공인회계사, 금전출납원, 기획사무 종사자, 비용회계사, 시설..."
4,[한국],[행과고],1,1,7,1,[홍길동],6,3,7,3,3,2,3,2,4,8,8,7,12,12,7,14,16,11,6,6,4,6,18,9,9,7,14,9,49,35,53,35,35,30,39,34,45,65,65,60,57,57,43,63,69,54,73,48,48,43,61,48,49,49,42,47,54.000000,44.333333,47.500000,50.666667,55.666667,46.000000,I,55.666667,S,54.000000,R,50.666667,C,47.500000,A,46.000000,E,44.333333,100.0,4.916667,IS,SI,5,1,T,I,IT,"사회계열학과(사회복지학과, 사회학과 등), 인문계열학과(사학과, 철학과 등), 약학...","보건의료 전문가(약사, 의사, 한의사 등), 사회과학 전문가(사회학자, 정치학자, ..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,[한국],[행과고],1,1,29,1,[홍길동],5,3,3,5,3,5,4,4,6,6,6,6,9,12,15,13,14,8,5,6,4,6,4,13,12,9,11,11,45,35,35,45,35,45,45,45,55,55,55,55,48,57,66,60,63,46,36,58,55,48,52,52,46,49,42,47,44.500000,47.833333,52.000000,52.166667,50.500000,48.166667,R,52.166667,C,52.000000,I,50.500000,A,48.166667,E,47.833333,S,44.500000,100.0,2.083333,RC,RI,4,3,T,I,IT,"기계공학과, 멀티미디어공학과, 반도체공학과, 전자공학과, 지질학과, 컴퓨터공학과, ...","건축기술자, 과학기기조작원, 귀금속가공사, 기계공학기술자, 선박기관사, 자동차정비사..."
9996,[한국],[행과고],2,4,8,1,[홍길동],5,4,4,3,5,3,6,6,4,5,4,5,7,12,13,10,11,11,2,9,4,7,12,2,12,12,8,8,45,40,40,35,45,35,55,55,45,50,45,50,43,57,60,51,54,54,55,30,55,55,46,46,35,58,42,50,47.666667,46.500000,50.000000,46.166667,48.166667,45.666667,C,50.000000,I,48.166667,S,47.666667,E,46.500000,R,46.166667,A,45.666667,100.0,2.666667,CI,CS,3,5,T,I,IT,"세무학과, 전자계산학과, 응용통계학과, 컴퓨터시스템학과, 회계학과 등",NaN
9997,[한국],[행과고],1,4,17,2,[홍길동],6,4,3,2,5,4,5,8,4,2,5,3,9,8,9,12,8,12,3,3,4,7,13,8,9,7,5,10,46,38,34,30,42,38,49,65,44,34,49,39,48,45,48,56,45,56,59,47,49,44,39,51,40,40,42,51,49.333333,46.333333,42.833333,41.666667,43.666667,46.333333,S,49.333333,E,46.333333,A,46.333333,I,43.666667,C,42.833333,R,41.666667,100.0,4.333333,SE,SA,1,2,T,D,DT,"관광경영학과, 교정학과, 사범대 사회계열학과, 사회복지학과, 사회사업학과, 신학과 등","공인노무사, 관광가이드, 교도관, 교육행정가, 사회복지사, 사회사업가, 사회서비스업..."
9998,[한국],[행과고],3,3,13,2,[홍길동],2,6,2,5,5,4,6,6,4,5,4,6,5,6,8,13,8,13,2,8,3,8,12,7,7,5,5,7,30,46,30,42,42,38,55,55,44,49,44,55,37,40,45,59,45,59,56,44,44,39,39,44,35,56,39,54,40.833333,45.166667,39.666667,48.333333,42.833333,48.833333,A,48.833333,R,48.333333,E,45.166667,I,42.833333,S,40.833333,C,39.666667,100.0,3.250000,AR,RA,6,4,T,I,IT,"무대예술학과, 무용학과, 방송영상과, 산업미술학과, 장식미술학과, 조소과 등","도자기공예기사, 메이크업 아티스트, 무대기술자, 사진작가, 상품진열전문가, 영화세트..."
9999,[한국],[행과고],1,3,15,1,[홍길동],2,3,4,5,2,8,2,7,6,7,9,6,9,6,8,9,11,10,3,6,5,3,14,10,10,7,11,11,30,35,40,45,30,57,34,60,55,60,70,55,48,41,46,48,54,51,61,50,50,43,52,52,39,49,45,39,41.833333,43.666667,46.166667,48.166667,48.333333,53.833333,A,53.833333,I,48.333333,R,48.166667,C,46.166667,E,43.666667,S,41.833333,100.0,6.583333,AI,AR,6,5,P,I,IP,"미술학과, 미술평론학과, 미학과, 음악학과, 작곡과 등","문학평론가, 민속예술가, 비평가, 영화․연극 및 방송관련 전문가, 음악․미술․영화평..."

In [96]:
df_factor.to_excel("C:\\Users\\user\\Desktop\\logic\\random_test_1129.xlsx")